### ISSUE TITLE
How can I notify the client if the user no longer has access to the document during editing?

### ISSUE THREAD

**Issue by DenysPoliarush** [ueberdosis/hocuspocus#130]
Hi guys! First off all, thanks for your work. It's amazing!

**Description**
In my project, I can give users access to edit projects or not. 

For example, I gave the user access to edit the project, the user connects to the project and edits it. After a while, I decided to take away the ability to edit from the user. The user should see all updates, but shouldn't edit anything.

How can I immediately inform the client from the server about this, in order to block the editor?  I don't need to close his connection, I just need to block his editor.

Also, if the auth token has expired, I would like to close the connection. I can do this with `connection.close()`, but in that case, I cannot send an error code and message.

On the server, I check user permission in the onChange hook, and if the user no longer has the ability to edit, I give him a `connection.readOnly = true`. And it works, what the user writes is not saved on the server. But I need also block his editor on the client.

And I also check user permission in the onConnect hook, and I need the same instruments here, but currently, I don't have connection as an instance of Connection here, I can only change readOnly mode

This is my code from server
```
async onConnect (data) {
    const permission = await checkPermission(someData);

     if (permission.code === 4000) { // read only
        data.connection.readOnly = true;
        // here I need to send to client message - like 'Read Only'
      } else if (permission.code >= 4400) { 
        // here I need to close connection, but with code and message.
        // data.connection.close(permission.code, permission.message) - don't work, because data.connection.close() is not a function
      }
}

async onChange (data) {
    for (const { connection } of data.document.connections.values()) {
      if (connection.socketId === data.socketId) {
        const permission = await checkPermission(someData);

        if (permission.code === 4300) { // can only read the document
          connection.readOnly = true;
          // connection.send('test');
        } else if (permission.code >= 4400) { // connection must be closed and never reconnect
          // here I need to close connection, but with code and message.
          // connection.close(permission.code, permission.message);
        }
      }
    }
}
```

Please, let me know if you have any ideas about it or if you have a better solution for solving this problem. 

Thanks!

**Comment by janthurau** [comment]
This is working now using `connection.sendStateless`
