### ISSUE TITLE
Check disconnecting state

### ISSUE THREAD

**Issue by hanspagel** [ueberdosis/hocuspocus#264]
> We've noticed that it sometimes takes a long time to detect when the client loses its connection to the Hocuspocus server, which is unfortunate because we want to show an error banner when the the user is disconnected.
> 
> When I've been testing this out by turning off the client's Internet connection, it takes about 90 seconds before the onClosed and onDisconnect callbacks are called. However, I noticed that the websocket enters the CLOSING state after just 30 seconds, but then it takes another 60 seconds before the websocket is CLOSED.
> 
> I'm thinking that it would be nice if the HocuspocusProvider somehow let its clients now already when the websocket enters the CLOSING state, so that we can show the error banner already at that point.
> 
> The HocuspocusProvider already defines three WebSocketStatuses 'connecting', 'connected' and 'disconnected', so do you think it would make sense to add a new 'disconnecting' state to that list?

**Comment by janthurau** [comment]
The websocket timeout depends on the browser implementation, it's much faster in Chrome than in Firefox.

The ping/pong interval can be configured when creating Hocuspocus:

```
const server = new Hocuspocus({timeout: 15})
```
