### ISSUE TITLE
Export `Connection` and `Document`

### ISSUE THREAD

**Issue by HalfVoxel** [ueberdosis/hocuspocus#272]
**The problem I am facing**
We use tokens to handle authentication. These tokens have an expiration time. Currently, it is not possible for us to close a connection when this token expires, unless the client actually sends us something (and even then, we would only be able to close it *after* the client's changes have already been made). We solve this by having a background task loop through all connections regularly and close the ones that are about to expire. However, while this works, we are not able to typecheck it because the Document and Connection types are not exported. Furthermore, some types are just typed as `any` in hocuspocus, which makes it harder too (e.g. `Hocuspocus.documents : Map<any,any>` instead of `Map<string, Document>`).

**The solution I would like**
Export `Document` and `Connection` and include these types wherever relevant.

CC: @ViktorQvarfordt

**Comment by janthurau** [comment]
I just tested this, seems it works now (Typescript 4.9.5)

![image](https://user-images.githubusercontent.com/896179/228534703-44864b1f-e112-4598-9d9d-4e46334404ae.png)
