### ISSUE TITLE
Send stateless messages over the existing websocket connection

### ISSUE THREAD

**Issue by ViktorQvarfordt** [ueberdosis/hocuspocus#279]
**The problem I am facing**

In collaborative applications one typically wants to send arbitrary stateless messages, for example to trigger an action on the server or on other connected clients. Hocupocus already establishes a websocket connection for synchronizing YDoc and YAwareness but both of these are stateful types of communication. Setting up a separate service for stateless messages would be unfortunate when we already have the websocket connection established by Hocuspocus.

**The solution I would like**

Ability to send client-to-server messages and broadcast messages. A broadcast message reaches all connected clients and the server, and can be initiated by either a client or the server.

For this we need a namespace but we already have a natural namespace identified by document name so I suggest we stick to that and keep it simple. (This may need to be coordinated with the thinking of subdocuments.)

Very rough usage sketch:

```ts
const provider = new HocuspocusProvider(..)
provider.broadcastMessage(data) // This message reaches all connected clients and server
provider.sendServerMessage(data) // This message reaches only the server and is initiated by a client
provider.on('message', (data, source) => ..) // source indicates a client id or server that initiated the message
// data should perhaps simply follow the websocket standard https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/send#parameters.
// It will be common for users to send json data, but the user can JSON.stringify/parse manually
```

The naming needs to be figured out. Hocuspocus currently has another event with the same name `.on('message')`.

This feature should scale horizontally together with the upcoming Redis scaling mechanism.

**Alternatives I have considered**

Setting up a completely separate websocket server and sending stateless messages through this service.

**Additional context**

I think this feature fits well in the overarching vision of Hocuspocus as I understand it: To provide the backend solution for collaborative and real-time applications. I believe avoiding separate infrastructure for sending stateless messages would be a big win for many users of Hocuspocus.

**Comment by janthurau** [comment]
Added in v1.1.0.

**Comment by adrice727** [comment]
Has anyone had success sending messages from a `provider`?  `document.broadcastStateless()` works fine, but when I call `provider.sendStateless()`, I don't receive the message on the server or in other providers.  I'm on version `1.1.1` for all `@hocuspocus` packages.

**Comment by janthurau** [comment]
@adrice727 can you share your code? I just tested, for me it works.

provider.sendStateless('test')

server:
``` 
async onStateless(data) {
    console.log(data)
  },
```

**Comment by adrice727** [comment]
@janthurau I wiped my `node_modules` and did a new build.  I'm seeing the message on the server now, but not other clients.  Is that the intended behavior?

**Comment by janthurau** [comment]
cool. yep, if you want to send messages to another client you have to relay it through the server and use server.broadcastStateless
