### ISSUE TITLE
[RFC] Road to beta

### ISSUE THREAD

**Issue by hanspagel** [ueberdosis/hocuspocus#283]
It’s amazing what we achieved with Hocuspocus already. The adoption is insane, it’s running in production in tons of apps already. BUT, we’re still in alpha, and in a pretty closed state. 👀

We’d like to transition to a more stable beta version soonish. Let’s keep track of what needs to be done in this issue:

- [x] #286
- [x] Release the new Redis extension
- [x] #376
- [x] Migrate all tests to AVA
- [x] Go through the documentation to reflect recent changes and see Hocuspocus from the developers perspective

Things we can do in a beta stage:

- [x] Incorporate feedback for the above changes
- [x] Improve the typing
- [x] Polish the documentation
- [x] Add tons of examples

This list can change in the future. 

Put your feedback/questions below 👇

**Comment by svenadlung** [comment]
I am closing this topic as we did publish the stable version. Please discuss other topics in dedicated issues 🙏.
