### ISSUE TITLE
Optional delay before closing document

### ISSUE THREAD

**Issue by georeith** [ueberdosis/hocuspocus#300]
**The problem I am facing**

Opening a document is the most resource intensive operation on the server for me (`applyUpdates` can take a very long time if there is a lot to garbage collect).

Currently we are susceptible to people refreshing documents in their browser triggering document close and reopens on the server if they are the only one connected.

**The solution I would like**

Add an optional period of time the server waits after the last person disconnects from a document before closing it, if someone else connects during this period the document is never released from memory and the `onLoadDocument` lifecycle not triggered.

**Comment by janthurau** [comment]
This has already been implemented here 😎  https://github.com/ueberdosis/hocuspocus/pull/683
