### ISSUE TITLE
HocusPocusProvider mistakenly stops reconnection attempts despite a token having been provided

### ISSUE THREAD

**Issue by bkempe** [ueberdosis/hocuspocus#313]
**Description**

[When HocusPocusProvider gets the Unauthorized code, it will not make reconnection attempts](https://github.com/ueberdosis/hocuspocus/blob/bf100bac8d842d228dceea52f25103e33a1a6d8f/packages/provider/src/HocuspocusProvider.ts#L553)

However, it looks like the only source of the Unauthorized event is [HocusPocus closing idle connections](https://github.com/ueberdosis/hocuspocus/blob/bf100bac8d842d228dceea52f25103e33a1a6d8f/packages/server/src/Hocuspocus.ts#L354).

I do not have a good way to reproduce this, but I have seen reconnect attempts being stopped despite a token being provided. Maybe it would be better to be explicit in the provider code whether a token was actually provided?
Also, the ability to hook into more aspects like
* Unauthorized event received
* closing idle connections
etc. would help. (I am extending the code now to gain more insight.)

**Steps to reproduce the bug**
Unfortunately no steps.

**Expected behavior**
Retrying to connect.

**Environment?**
 - operating system: Mac OS 10.15.7
 - browser: Chrome 98.0.4758.109
 - mobile/desktop: Desktop
 - hocuspocus version: 1.0.0-alpha.11

**Comment by janthurau** [comment]
Is this still happening? Can't reproduce it, but if someone gets this error, please share used extensions, versions, and the Hocuspocus server logs. We've added a lot of error reporting since then, so maybe that can help. Or maybe it's just already fixed :-)
