### ISSUE TITLE
Use 1 WS connection to fetch documents instead of establishing connection for each documents

### ISSUE THREAD

**Issue by shahriar-shojib** [ueberdosis/hocuspocus#343]
Right now hocuspocus provider opens WS connection each time the document needs to change, instead, it should use one connection to handle document changes.

In addition to that, hocuspocus provider should have a plugin system like hocuspocus server where it should be possible to store documents in memory/browser's local storage or implement offline capabilities.

Right now, changing to another document and getting back to the previous document causes the provider to fetch the document from the server before the contents are shown in the editor. Implementing something like this will give us the opportunity to improve the UX of whatever it is we're trying to build.

**Comment by janthurau** [comment]
https://github.com/ueberdosis/hocuspocus/releases/tag/v2.0.0-beta.0
