### ISSUE TITLE
Fix for: "Yjs was already imported. Importing different versions of Yjs often leads to issues."

### ISSUE THREAD

**Issue by brandonraphael** [ueberdosis/hocuspocus#358]
**Description**
According to the YJS code below, YJS does a `console.warn` message whenever multiple versions of YJS are found. ClickUp uses HocusPocus (and YJS) for co-editing. We would like this warn message removed/disabled.

We currently use ESM imports to interact with YJS, e.g. : `import { YjsServer } from '../impl/yjs';`
HocusPocus imports CJS YJS modules, e.g. : `var Y = requre('yjs');`
It appears these two types of imports are likely causing the below warning.

The [YJS code](https://unpkg.com/yjs@13.5.21/dist/yjs.cjs) creating the warn:
```
const glo = /** @type {any} */ (typeof window !== 'undefined'
  ? window
  : typeof global !== 'undefined' ? global : {});
const importIdentifier = '__ $YJS$ __';

if (glo[importIdentifier] === true) {
  /**
   * Dear reader of this warning message. Please take this seriously.
   *
   * If you see this message, please make sure that you only import one version of Yjs. In many cases,
   * your package manager installs two versions of Yjs that are used by different packages within your project.
   * Another reason for this message is that some parts of your project use the commonjs version of Yjs
   * and others use the EcmaScript version of Yjs.
   *
   * This often leads to issues that are hard to debug. We often need to perform constructor checks,
   * e.g. `struct instanceof GC`. If you imported different versions of Yjs, it is impossible for us to
   * do the constructor checks anymore - which might break the CRDT algorithm.
   */
  console.warn('Yjs was already imported. Importing different versions of Yjs often leads to issues.');
}
```

**Steps to reproduce the bug**
1. Import YJS as an ESM _and_ CJS module into a node project. (alternatively import HocusPocus into a project with an existing ESM import of YJS).
2. Run the node project.
3. The warning message `Yjs was already imported. Importing different versions of Yjs often leads to issues.` Should be visible.

**Expected behavior**
We expect the warn to not appear in our console as we use HocusPocus.

**Screenshot, video, or GIF**
hocuspocus and y-prosemirror node modules using CJS imports:
![Screen Shot 2022-06-01 at 12 26 00 PM](https://user-images.githubusercontent.com/17938901/175413817-e6059489-7f52-4609-ab1d-b7aa52ff9dfb.png)

**Environment?**
 - operating system: OSX
 - browser: Chrome
 - mobile/desktop: desktop
 - hocuspocus version: "1.0.0-alpha.11"

**Additional context**

**Comment by srsudar** [comment]
We also saw this, and our issue was due to server side rendering, as best I can tell. Posted my fix here:

https://github.com/yjs/yjs/issues/438#issuecomment-1452586225
