### ISSUE TITLE
Memory heap after update to last version 1.0.0-beta.6

### ISSUE THREAD

**Issue by MakarovCode** [ueberdosis/hocuspocus#457]
**Description**
We've been running hocuspocus in production deployed on Heroku for a couple of weeks now and decided to upgrade to the last version (1.0.0-beta.6) from the 1.0.0-alpha.103 because of some crashing issues. Now it is not crashing but we notice a increase in memory usage, something we haven't experienced before. (See image below)

**Screenshot, video, or GIF**
![image](https://user-images.githubusercontent.com/1951749/206740098-ffa115d9-a5d2-46fe-b4f9-a24763cd5b24.png)

**Environment?**
 - HEROKU
 - hocuspocus version: 1.0.0-beta.6

**Comment by janthurau** [comment]
hey @MakarovCode, we've fixed the issue in our cluster by upgrading yjs peer dependencies. Let me know if you're still experiencing issues.

Closed for now :-)
