### ISSUE TITLE
My proposal for refactoring the documentation

### ISSUE THREAD

**Issue by EgonBolton** [ueberdosis/hocuspocus#482]
Congratulations on the stable release, and thank you so much for the amazing job you've done!

I'm an organization and documentation nerd 🤓, so I'd like to share my proposal to make the Hocuspocus documentation more clear.

The structure would be like this:
```
Overview
  Introduction
  Getting Started
  About the Project
  Contributing

Server
  Settings
  Methods
  Hooks*
  Extensions*
  Examples*

Provider
  Introduction
  Settings
  Events
  Examples*

Guides
  Authorization
  Persistence
  Multi/Sub-Documents
  Scalability
  Awareness
  Custom Extensions
```

Next I explain in more detail the changes of my proposal (some of which are evident with the previous structure and others are not):

- Make the main sections (`Overview`, `Server`, `Provider` and `Guides`) collapsible.
- Move the `Quick Start` subheading in the `Introduction` sub-section to `Installation` (there's already something very similar there, almost duplicated) and rename `Installation` to `Getting Started`.
- The `Awareness` sub-section is almost duplicated in the `Use Case` and `Provider` sections. I would consolidate them into a single sub-section under the Guides category, and make sure that `Guides > Awareness` and `Provider > Events` reference each other via a hyperlink.
- The rest of the sub-sections under `Use Case` move to `Provider > Examples`.
- Move the current sub-sub-sections under `Overview > installation` (Express, Koa, CLI, etc) to `Server > Examples`.
- Convert the `Server > Configuration`, `Server > Methods`, and `Provider > Configuration` sub-sections to tables instead of articles, as you already do with `Server > Hooks`. Due to the structured nature of the article, a table is much easier to scan than an article in such cases. The subtitle `Usage` at the end of those sections is nice and I would leave it that way.
- Delete the `Provider > Installation` section. The `Server` section doesn't have his, and the installation instructions are already mentioned in `Overview`. A hyperlink could be added at the top of `Provider > Introduction` to `Overview > Getting Started` for installation instructions.
- In the `Guides`, I would remove `Configuration` and `Hooks` as they are duplicate in the `Server` section. The `Documents`, `Working with JSON` and `Subdocuments` sections, I would refactor to two different guides: `Persistence` and `Multi/Sub-Documents`
- As you can see, the new structure that I propose is 2 levels deep, instead of 3. That is because the sections that I have marked with an asterisk have a table as content, with additional explanatory subheadings. If you're worried that people won't find that content because it's not in the sidebar, keep in mind that Algolia identifies the titles, and people will likely find the relevant links in the `Guides` section to the `Server` or `Provider` sections. ".

In my opinion that would be much clearer :)

I think if you like these suggestions I can collaborate with a PR. I see that the documentation consists of .md files with a .yml defining the structure. The only thing I'm not sure how to do is (1) make the main sections collapsible, and (2) run the documentation locally to see and debug the changes.

**Comment by janthurau** [comment]
hey @EgonBolton, thanks a lot! These changes make a lot of sense.

Seeing a PR for this would be amazing :-) Unfortunately, I don't really know how to run the current docs locally, as they are [somehow] integrated with the Tiptap docs. I'll check with the team and get back on that..

Will also check:
* How to add Algolia search (we have it on Tiptap docs, but not on Hocuspocus)
* How to make navigation items collapsible

**Comment by EgonBolton** [comment]
I'm glad you liked it, and it will be a pleasure to help with the PR!

Now that you mention it, I think I read somewhere that you were planning to move Hocuspocus to its own website, although I don't know if you still have that intention?

Anyway, I'll wait for your response, at least in regards to running the docs locally, as it will allow me to get the job done faster and assess UX/UI issues on the fly.

**Comment by mkriegeskorte** [comment]
Hey @EgonBolton!

Thanks for your thoughts. I like them, too! Unfortunately the documentation is deeply integrated into the website which is private because it handles some other stuff. I guess we’re able to separate those again in the future, but I can’t give you an ETA for that.

I’d suggest to open a branch with your changes to the `*.md` files and `links.yaml` and just hand it over to me. I’ll try to fix anything related to the navigation or UI issues along the way. If you’re unsure how to adjust the structure, just leave a comment in the `links.yaml`.

Does that makes sense for you?
