### ISSUE TITLE
Awareness seams not to work properly 

### ISSUE THREAD

**Issue by andrezimpel** [ueberdosis/hocuspocus#494]
**Description**
I am using the playground from the repo. Even there the awareness states are not correctly synced between browsers. It works within the same browser but in different tabs/windows tho. Firefox does not work at all showing both the connect and disconnect buttons.

**Steps to reproduce the bug**
Clone the repo and run the playground as started in the readme. 

**Expected behavior**
All active users for a document should be synced as described in the docs. 

**Environment?**
 - operating system: MacOs iOS
 - browser: Safari, Chrome, Firefox 
 - mobile/desktop: Mobile and Desktop
 - hocuspocus version: 1.0

**Comment by janthurau** [comment]
Closing this, let me know if you're still facing issues @andrezimpel
