### ISSUE TITLE
Server crashes when webhook returns 403 onDisconnect

### ISSUE THREAD

**Issue by fredpedersen** [ueberdosis/hocuspocus#498]
**Description**
Using the hocuspocus-laravel package, if the user is not authorised the package throws `new AuthorizationException("User is not allowed to access this document");`.

This works when onConnect is attempted, the server remains active only outputting `Caught error in extension-webhook: AxiosError: Request failed with status code 403`.

If the permission is removed while the connection is active, however, when the user disconnects the server crashes:
```
node Server.mjs
[onDisconnect] Request failed with status code 403
[onDisconnect] Request failed with status code 403

/node_modules/axios/lib/core/settle.js:19
    reject(new AxiosError(
           ^
AxiosError: Request failed with status code 403
    at settle (/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/node_modules/axios/lib/adapters/http.js:512:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_REQUEST',
```

**Environment?**
 - hocuspocus version: 1.0.0

**Comment by janthurau** [comment]
Thanks! I've wrapped all http calls in extension-webhook in try/catch blocks, so the server should not crash anymore 🥳
