### ISSUE TITLE
Sharing entire editor content with new client

### ISSUE THREAD

**Issue by wouter-deen** [ueberdosis/hocuspocus#507]
**Part of the documentation?**
Working with a database.

**Hard to understand, missing or misleading**
Every time a new client connects to the same room on the WebSocket, you want them to have as initial state the same content as all the other active users. After that, you only want to broadcast updates through the WebSocket connection. However, with the current debounce, if a new client connects and they fetch the data from the editor, it's possible that they are missing some words that the other clients added in the meantime. At least, that's how I'm interpreting it, since WebSockets are only used for sending updates, not the entire editor content. Is there any way to share the entire editor state when a new client connects (that's fully up-to-date), rather than only the updates after a client connects?

Edit: with fetching the data from the editor, I mean fetching it from the database.

**Additional context**
A video where you can see what I mean:
https://user-images.githubusercontent.com/62772323/216765975-ca5ababd-14ad-4df6-81c6-788cc0be32c3.mp4

**Comment by janthurau** [comment]
hey @wouter-deen, without seeing your code, it looks like the problem has the same cause as this one: https://github.com/ueberdosis/hocuspocus/issues/509

It's important to work with the ydoc on the server (see extension-database, https://tiptap.dev/hocuspocus/api/extensions/database), and not to set the content directly. If you still have issues, please post the server and provider part.

**Comment by wouter-deen** [comment]
Hi Jan, thank you for your reply. I do not believe that this is the problem. The [example on the TipTap website](https://tiptap.dev/examples/collaborative-editing) also does not have a database connected to it (as can be seen in the backend code), however, there the entire content of the editor gets sent to a new user. Did they just leave the database part out, or should that work out of the box?

For simplicity's sake, I removed the database in the code below. This still yields me the same problem as can be seen in the video that I posted in the original message. Please note that this code is running in NextJS and the `TextEditor` component is imported using [dynamic imports](https://nextjs.org/docs/advanced-features/dynamic-import) with SSR disabled. This is because NodeJS does obviously not support WebSockets, which prevents SSR.

```tsx
export default function TextEditor({ courseId, topicId, w, maxW, defaultContent }: EditorProps) {
  const {data: session} = useSession();
  const user = session?.user;
  const router = useRouter();

  const [editorContent, setEditorContent] = useState(null);
  const [status, setStatus] = useState();
  const [, updateState] = useState<{}>();

  /**
   * Method for re-rendering components after typing or moving the cursor. The editor does not update itself after
   * calling a function on it (e.g. toggleBold(), due to the usage of the useEffect hook for setting the editor in a useState.
   */
  const forceUpdate = useCallback(() => updateState({}), []);

  const ydoc = useMemo(() => {
    return new Y.Doc();
  }, []);

  const websocketProvider = useMemo(() => {
    return new HocuspocusProvider({
      name: process.env.NEXT_PUBLIC_INSTANCE_NAME + router.query,
      url: "wss://editor.heatwav.es",
      document: ydoc,
      connect: false,
      token: "token"
    });
  }, [ydoc]);

  // Connect to websocket
  useLayoutEffect(() => {
    if (websocketProvider.status == WebSocketStatus.Disconnected) {
      websocketProvider.connect();
    }

    return () => {
      if (websocketProvider.status == WebSocketStatus.Connected) {
        websocketProvider.destroy();
      }
    };
  }, []);

  const extensions = useMemo(() => {
    return [
      StarterKit.configure({
        codeBlock: false,
        history: false
      }),
      Highlight,
      Underline,
      Color,
      TextStyle,
      Superscript,
      Subscript,
      CharacterCount,
      Image,
      Youtube.configure({
        interfaceLanguage: router.locale,
        nocookie: true,
        ivLoadPolicy: 3,
        modestBranding: true,
      }),
      Link.configure({
        openOnClick: false,
      }),
      CodeBlockLowlight.configure({
        lowlight
      }),
      Collaboration.configure({
        document: websocketProvider.document
      }),
      CollaborationCursor.configure({
        provider: websocketProvider,
        user: {
          name: user?.name
        }
      }),
    ];
  }, [ydoc]);

  const [editor, setEditor] = useState<Editor | null>(null);

  useEffect(() => {
    const editor = new Editor({
      extensions,
      onTransaction({editor}) {
        setEditorContent(editor.getHTML());
        forceUpdate();
      },
      content: editorContent,
    });

    setEditor(editor);

    return () => {
      editor?.destroy();
      setEditor(null);
    };
  }, [extensions]);

  useEffect(() => {
    // Update status changes
    websocketProvider.on('status', event => {
      setStatus(event.status)
    })
  }, [])

  return (
    <Box borderWidth="3px"
         borderColor={useColorModeValue("gray.200", "whiteAlpha.200")}
         rounded="md"
         maxW={maxW}
         w={w}
    >
      <Toolbar editor={editor} courseId={courseId} topicId={topicId}/>

      <Box px={4} py={4}>
        <EditorContent editor={editor} spellCheck="true"/>
      </Box>

      <BottomBar editor={editor} status={status}/>
    </Box>
  )
}
```
And the server code:
```js
import { Server } from '@hocuspocus/server'

const server = Server.configure({
  name: 'heatwaves-ws-editor',
  port: 80,
  timeout: 30000,
})

console.log("HocusPocus server started")
server.listen()
```

**Comment by janthurau** [comment]
Unfortunately, I've never used next SSR, but what you want to achieve should work out of the box. The tiptap website also uses a database in the backend which stores to a PostgreSQL database, but regardless, even without a database the sync should work completely.

I'm not sure if your useMemo / useEffect calls are correct, maybe you can check this out, I think it's related to SSR: https://discord.com/channels/818568566479257641/841708462500085810/1021183143371362437

**Comment by wouter-deen** [comment]
Thanks a lot! At least now I know that it should sync the whole editor's content out of the box once a new client connects, even without a database connection, and that the problem is likely with my useEffect-like React calls.
