### ISSUE TITLE
Auth failed in webhook extension throws errors instead of using permissionDeniedHandler

### ISSUE THREAD

**Issue by fredpedersen** [ueberdosis/hocuspocus#508]
**Description**
The webhook extension currently just throws errors to the console when auth fails, instead of using `permissionDeniedHandler ` and ultimately triggering `onAuthenticationFailed` in the provider.

```
} catch (e) {
      console.error(`Caught error in extension-webhook: ${e}`)
      throw Forbidden
    }
```

**Expected behavior**
The webhook should be properly integrated with the server auth system, and when authentication via the webhook fails it should return a proper auth failed message to the provider and thus call the `onAuthenticationFailed` handler.

**Comment by janthurau** [comment]
Thanks! The `onConnect` hook is not meant for authentication purposes, I've just pushed an update to remove the paragraph from the docs.

If you want to set up authentication, the best way right now is to implement this on your own as a `onAuthenticate` hook on the server. This method can just call your webhook and everything should work fine. As carecodex mentioned in PR #506, a slow onConnect response will allow someone to access the document before the connection gets rejected.
