### ISSUE TITLE
How to send messages to clients

### ISSUE THREAD

**Issue by HengCC** [ueberdosis/hocuspocus#515]
How to actively communicate with the client during collaborative editing. For example, I want to notify each client when the last persistence time was, or tips the client when the persistence fails (maybe other persistence services are offline),then they can do something  accordingly.

Is there such a mechanism now? I have not seen relevant documents

**Comment by janthurau** [comment]
hey @HengCC, we don't have that implemented at the moment, but there's an open pull request, feel free to let us know if that would suffice for your case :)

https://github.com/ueberdosis/hocuspocus/pull/516

**Comment by HengCC** [comment]
thanks, that's what i want . expect it to be merged
