### ISSUE TITLE
Editor is never synced, unless forceSyncInterval is set

### ISSUE THREAD

**Issue by wouter-deen** [ueberdosis/hocuspocus#525]
**Description**
I'm using NextJS in combination with Tiptap and a Hocuspocus backend (running on a separate server, not via a NextJS api route). I have had syncing issues from the start. From talking to @varun-raj, who had the exact same problem in combination with NextJS, he identified a temporary solution which is to set the `forceSyncInterval` to some arbitrary (relatively low) number, like 200 ms. For clarity, this problem persists while running the out-of-the-box configuration of Hocuspocus, no database connected and no settings changed.

**Steps to reproduce the bug**
The architecture of my frontend is as follows. There is a TextEditor component, which creates the `new HocuspocusProvider`. Once the provider is created, this TextEditor component will call the `useEditor` hook and return the `EditorContent`, together with a toolbar and a bottom bar. This works fine when both users connect to the same room first, after which they start typing. However, if one user starts typing, and another user joins, that user will not receive the initial content. This can be confirmed by attaching the `onSynced` listener by passing it into the constructor and adding a log to the console. The message will never get logged, i.e., the initial content of the editor is never synced, unless the `forceSyncInterval` is set. It happens over HTTP and HTTPS, with and without a proxy. My Hocuspocus server is run on Google Cloud Run.

## Relevant code
Below you can find my own `useCollaborativeEditor` hook, which I've copied from someone on Discord, and adjusted to my needs.
```ts
const useCollaborativeEditor = (url, token, id) => {
  const [document] = useState(() => new Y.Doc())
  const [provider, setProvider] = useState<HocuspocusProvider | null>(null)

  useLayoutEffect(() => {
    const name = `file.${id}`

    const provider = new HocuspocusProvider({ url, token, name, document,
      forceSyncInterval: 200,
    })

    setProvider(provider)

    return () => {
      if (provider.status === WebSocketStatus.Connected) {
        provider?.destroy()
        setProvider(null)
      }
    }
  }, [id, token, document, url])

  return { provider, document }
}

const {provider, document} = useCollaborativeEditor("wss://editor.heatwav.es", "token",
  courseId + topicId + roomIdModifier ?? "");

if (!provider) return null;`
```
If the provider is not falsy (i.e., has been initalized), call the `useEditor` hook and return the actual EditorContent component:
```ts
const editor = useEditor({
  extensions: [
    StarterKit.configure({
      codeBlock: false,
      history: false
    }),
    Highlight,
    Underline,
    Color,
    TextStyle,
    Superscript,
    Subscript,
    CharacterCount,
    Image,
    Youtube.configure({
      interfaceLanguage: router.locale,
      nocookie: true,
      ivLoadPolicy: 3,
      modestBranding: true,
    }),
    Link.configure({
      openOnClick: false,
    }),
    CodeBlockLowlight.configure({
      lowlight
    }),
    Collaboration.configure({
      document: document
    }),
    CollaborationCursor.configure({
      provider: provider,
      user: {
        name: user?.name
      }
    }),
  ],
  onUpdate({ editor }) {
    setContent(editor.getHTML());
  },
})
```

**Expected behavior**
The `HocuspocusProvider` should sync immediately after connecting to the Hocuspocus server, and not need a `forceSyncInterval`.

**Screenshot, video, or GIF**
https://user-images.githubusercontent.com/62772323/223110229-158446f5-8e5d-40a2-b296-63687fb100bb.mp4

**Environment?**
 - operating system: Windows and Mac
 - browser: Chrome, Brave, Safari
 - mobile/desktop: both
 - hocuspocus version: 1.0.0

**Comment by svenadlung** [comment]
@wouter-deen 

Unfortunately, I can not reproduce your troubles at all.

I took your code and built both the client side with Next.js and the Hocuspocus server from scratch. 

Everything worked without any problems. 

- Does it work locally? Let's try to isolate the error.
- Can you create a minimal CodeSandbox which I can then connect to?

This is the code I was currently using:

```
"use client";

import { useLayoutEffect, useState } from "react";
import * as Y from "yjs";
import { useEditor, EditorContent } from "@tiptap/react";
import { StarterKit } from "@tiptap/starter-kit";
import { Collaboration } from "@tiptap/extension-collaboration";
import { HocuspocusProvider } from "@hocuspocus/provider";

const useCollaborativeEditor = (url: string, token: string, id: string) => {
  const [document] = useState(() => new Y.Doc());
  const [provider, setProvider] = useState<HocuspocusProvider | null>(null);

  useLayoutEffect(() => {
    const name = `file.${id}`;

    const provider = new HocuspocusProvider({
      url,
      name,
      document,
      onSynced: ({ state }) => {
        console.log(state);
      },
    });

    setProvider(provider);

    return () => {
      provider?.destroy();
      setProvider(null);
    };
  }, [id, token, document, url]);

  return { provider, document };
};

const Tiptap = () => {
  const { provider, document } = useCollaborativeEditor(
    "ws://127.0.0.1:1234",
    "token",
    "test"
  );

  const editor = useEditor({
    extensions: [
      StarterKit.configure({
        history: false,
      }),
      Collaboration.configure({
        document: document,
      }),
    ],
  });

  if (!provider) {
    return null;
  }

  return <EditorContent editor={editor} />;
};

export default Tiptap;
```

**Comment by wouter-deen** [comment]
Hi @svenadlung, thank you for your efforts. I realized I made the mistake of not posting the version of Hocuspocus that I'm using. I used the original version 1.0, and since then a lot has changed and the problem is not there anymore. Furthermore, I was using NextJS 12 and not 13, so "use client" was not a thing yet.
