### ISSUE TITLE
How to convert the document content stored in Uint8Array into understandable plaintext content

### ISSUE THREAD

**Issue by HengCC** [ueberdosis/hocuspocus#528]
We hope to store a plaintext content through the backup to provide full-text retrieval. But I don't know how to convert the stored binary string into something that can be used by the tokenizer.  I haven't seen relevant documents to support this requirement.

**Comment by janthurau** [comment]
hey @HengCC, if you are using TipTap, you can use this: https://tiptap.dev/hocuspocus/guide/transformations#tiptap

**Comment by HengCC** [comment]
thks. i'll try it.
