### ISSUE TITLE
redis prefix may cause `MessageReceiver` not working as expected

### ISSUE THREAD

**Issue by HengCC** [ueberdosis/hocuspocus#531]
see code 
```js
private handleIncomingMessage = async (channel: Buffer, pattern: Buffer, data: Buffer) => {
    const channelName = pattern.toString()
    const [_, documentName, identifier] = channelName.split(':')
    const document = this.documents.get(documentName)

    if (identifier === this.configuration.identifier) {
      return
    }

    if (!document) {
      return
    }

    new MessageReceiver(
      new IncomingMessage(data),
      this.logger,
    ).apply(document, undefined, reply => {
      return this.pub.publishBuffer(
        this.pubKey(document.name),
        Buffer.from(reply),
      )
    })
  }
```
note  the line below:

https://github.com/ueberdosis/hocuspocus/blob/476898bfb892227ea9fbd18433e01e9717b9d549/packages/extension-redis/src/Redis.ts#L268

In this line of code, the format of `channelName` is similar to `prefix:documentName:hostIdentity`, where the prefix is allowed to be customized. When the prefix contains ":", it may become the format which like  `prefix::documentName:hostIdentity` , note that there is an extra ":", which will cause the value of this code to not meet expectations, it will cause `MessageReceiver` to never work normally. It is recommended to deal with `prefix`. Remove the ":"

**Comment by HengCC** [comment]
Also, if there is ":" in `documentName`, this will also happen. Of course, this value will not appear in most cases.

**Comment by janthurau** [comment]
Thanks for the report!

Not sure what's the best fix here, if you are hitting this bug right now feel free to open a PR with a proposed change :-) The easiest would probably just taking a longer/better delimiter, but maybe we can just move the documentName to the message itself. I did this in feature/multiplexing (not for redis though), but probably something similar could be done.

**Comment by HengCC** [comment]
Perhaps the convention could be better. Add some explanations in the documentation. It is recommended not to use strings with ":". When users really need ":" in the prefix, let users choose a separator other than ":" character as a configuration input parameter. But the default separator is still ":"

Or use some special characters as the default separator. For example
"__hocuspocus__", the overall purpose is also to avoid conflicts with user-defined prefixes as much as possible
