### ISSUE TITLE
TypeScript does not find types with ESM and `node16` module resolution

### ISSUE THREAD

**Issue by reknih** [ueberdosis/hocuspocus#537]
TypeScript fails to locate the types for `@hocuspocus/server` when `moduleResolution` is set to `node16`. Changing it to `node` fixes the issue. However, `node16` module resolution is often necessary for native ESM projects.

I am running Node 18.4.0 and TypeScript 4.9.5 on macOS 13.2.1 (ARM).

The configuration files and exact error messages can be found below:

<details>
<summary>tsconfig.json</summary>

```json
{
    "include": [
        "src/**/*"
    ],
    "compilerOptions": {
        "outDir": "dist",
        "rootDir": "src",
        "sourceMap": true,
        "strict": true,
        "esModuleInterop": true,
        "module": "ES2020",
        "target": "es2021",
        "moduleResolution": "node16",
        "resolveJsonModule": true,
        "declaration": true,
        "declarationMap": true
    }
}
```
</details>

<details>
<summary>Error message</summary>

```
Could not find a declaration file for module '@hocuspocus/server'. '/Users/user/code/hpnext/node_modules/@hocuspocus/server/dist/hocuspocus-server.cjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/hocuspocus__server` if it exists or add a new declaration (.d.ts) file containing `declare module '@hocuspocus/server';`ts(7016)
```
</details>

<details>
<summary>index.ts</summary>

```ts
import { Server } from '@hocuspocus/server'

const server = Server.configure({
  port: 80,

  async onConnect() {
    console.log('🔮')
  },
})

server.listen()
```
</details>

**Comment by janthurau** [comment]
thx for the report! Do you know how to fix this? I'm not that experienced with how the resolution works :-) I reproduced the issue with newer typescript and node16 resolution, but not sure how we can fix this without breaking it for older versions?

**Comment by reknih** [comment]
I'm not sure -- for the moment I am working with a fork that I switched over to `node16` resolution and appending `.js` file endings to local imports. You'd also need to add a `"types": "./dist/packages/server/src/index.d.ts"` (analog for other packages in the workspace) to the `exports`/`default` path of the `package.json`s.

I did not test whether or not this breaks backwards compatibility with any old Node versions or CommonJS.

**Comment by gustavhartz** [comment]
@reknih - did you come up with a solution?

**Comment by reknih** [comment]
I am manually patching my local build with the changes I mentioned in my previous comment. They should, by the way, be compatible with older module resolution algorithms as well since they are strictly more specific.

**Comment by janthurau** [comment]
@reknih any chance to get your patch file? I've just merged a PR that adds the additional typing exports, but from my test we'd still have to go through everything and adjust the imports manually, so if you did that already, that would be great :-)

**Comment by reknih** [comment]
I attached my patches for `server`, `common`, and `extension-throttle`. They are based on 2.0.1 and the `server` patch is super messy because it also applies a bugfix on a branch that was, at that time, unreleased. Hope that helps!

[@hocuspocus+common+2.0.1.patch](https://github.com/ueberdosis/hocuspocus/files/11475563/%40hocuspocus%2Bcommon%2B2.0.1.patch)
[@hocuspocus+extension-throttle+2.0.1.patch](https://github.com/ueberdosis/hocuspocus/files/11475564/%40hocuspocus%2Bextension-throttle%2B2.0.1.patch)
[@hocuspocus+server+2.0.1.patch](https://github.com/ueberdosis/hocuspocus/files/11475565/%40hocuspocus%2Bserver%2B2.0.1.patch)
