### ISSUE TITLE
Document's attributes lost when run through Transformer

### ISSUE THREAD

**Issue by WilliamIPark** [ueberdosis/hocuspocus#547]
**Description**
If we have a document's content in JSON format, and we try to transform that into a ydoc using TiptapTransformer, in the process we lose any attributes that the document had before.

**Steps to reproduce the bug**
Full reproducible example:
https://codesandbox.io/p/sandbox/eager-cherry-xm9vqg?file=%2Findex.mjs

**Expected behavior**
The documents attributes still remain, and are not stripped away.

**Environment?**
 - hocuspocus version: 1.1.3

**Comment by janthurau** [comment]
That's a missing feature in y-prosemirror (https://github.com/yjs/y-prosemirror/issues/48), nothing we can do here :(
