### ISSUE TITLE
[onConnect] self._addDefaultMeta is not a function

### ISSUE THREAD

**Issue by martin-cycle** [ueberdosis/hocuspocus#549]
**Description**
I cannot use the Logger extension

**Steps to reproduce the bug**
I installed the logger extension as explained in the documentation but I cannot make it work. I keep getting the `[onConnect] self._addDefaultMeta is not a function` message, my RT editor not working when opening it.

**Expected behavior**
I expect the logger to work as expected without preventing me from using the editor

**Screenshot, video, or GIF**
The messages from my terminal:
![Screenshot 2023-03-29 at 10 00 31](https://user-images.githubusercontent.com/66952775/228466742-cbcf030d-8f37-440f-aa5d-858d13a24f3f.png)
The editor not loading:
<img width="1117" alt="Screenshot 2023-03-29 at 10 01 02" src="https://user-images.githubusercontent.com/66952775/228466867-6a48eaf6-f631-4cd1-b3cc-578b53886469.png">

**Environment?**
 - operating system: docker node 16 on macOS montery 12
 - browser: chrome 111.0.5563.110
 - mobile/desktop: desktop
 - hocuspocus version: 1.1.3

**Comment by janthurau** [comment]
hey @martin-cycle, I'm using the logger extension as well and I'm not facing any issues, can you share your logger configuration? We're not using a addDefaultMeta method, probably you are using winston? 🤔  https://github.com/winstonjs/winston/issues/1591

**Comment by martin-cycle** [comment]
You're right, my bad! Thanks for your quick reply!!
