### ISSUE TITLE
v2 will not reauthenticate upon re-connect

### ISSUE THREAD

**Issue by reknih** [ueberdosis/hocuspocus#566]
When the `HocuspocusProviderWebsocket` re-establishes the connection to a server with required authentication after some time being offline, its bound `HocuspocusProvider`s will not retransmit their auth tokens because their `isAuthenticated` property is true. Instead, server authentication will fail, and the server will transmit an `Unauthorized` code and close the connection to forbid the client to retry.

**Reproduction:**

- Use a multiplexing-capable version of Hocuspocus server and clients
- Have the client join a server that shall require authentication through an `onAuthenticate` function for all inbound connections
- Cut the connection between client and server
- *Await the server's timeout so that it closes the client socket and voids its authentication*
- Re-Establish the connection between client and server
- A new socket will be created, communication will fail with the error message ``[HocuspocusProvider] An authentication token is required, but you didn’t send one. Try adding a `token` to your HocuspocusProvider configuration. Won’t try again.``

I can reproduce this bug with Node v18.4.0, Chrome 111, and Safari 16.3 on macOS 13.2.1

**Comment by joshua7v** [comment]
I probably hit the same issue here. 
I was trying to figure out why the connect get closed after several seconds and never reconnect back.
And I notice the exact same warning in the console
`[HocuspocusProvider] An authentication token is required, but you didn’t send one.`

I'm a first-day user, and the warning looks quite clear, at first glance at least.
I thought all its complaining is I did not add the token in config as this doc states: https://tiptap.dev/hocuspocus/guides/auth
but seems its not that simple, adding the token does not make any difference
now I'm lost and have no idea how to fix that 😢

**Comment by janthurau** [comment]
hmm, I just tried reproduce this but it just works here. When turning connectivity back on, a new websocket starts with this auth message:

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/896179/231260208-afb3266f-35f4-4936-a621-b87ee70646e8.png">

**Comment by stedabee** [comment]
Any updates on this? We have the same issue here. If we either pass or not token, the warning message occurs, changing something inside the provider, causing a restart in my case. We are using hocuspocus server & provider 2+ .

**Comment by janthurau** [comment]
@stedabee I couldnt reproduce this, but have added another safeguard in v2.0.6. Are you using this version in the provider?

**Comment by janthurau** [comment]
I'm still unable to reproduce this. Can you reproduce this in our playground? I've set up a connection with a token to Hocuspocus (onAuthenticate hook defined), connected + typed something into Tiptap. Then I've just unplugged my LAN cable until the retry logic started (in my case after around 60 seconds in Chrome). I plugged it back in, and the new websocket contained the AUTH message and connected properly. Anything I'm overseeing?

Hocuspocus is removing the connection timeout after onConnect / onAuthenticate hooks finished. Are they taking a long time in your case? The provider will drop this message if the connection got closed with UNAUTHORIZED, so it's possible that another condition triggers this. Would also be helpful to see the last few websocket messages that were sent/received.

**Comment by DenysPoliarush** [comment]
Hi @janthurau 
This is the last message that was sent/received and then the Error `Invalid frame header` 
![Screenshot 2023-05-15 at 13 15 21](https://github.com/ueberdosis/hocuspocus/assets/66991536/300474b1-11d5-489a-b967-728cef0eb320)

And this is in the console. The connection was closed with the error code 4401. 
![Screenshot 2023-05-15 at 13 16 55](https://github.com/ueberdosis/hocuspocus/assets/66991536/04df83f5-ddf1-4325-bb1e-ce9f579ee13d)

**Comment by janthurau** [comment]
Unfortunately I cannot reproduce this, if someone can provide me with a sandbox / replit or other way to reproduce this (for example in the playground), I'll have a look right away. I just spent some more time trying, but it doesn't make sense - the only way to send the `Unauthorized` code is either a server error (would appear in the server logs), or the connection hasn't been established properly, but I don't neither see how it could happen nor can I reproduce it.

**Comment by jjgmckenzie** [comment]
For what it's worth, I have had this bug appear in my console, using a dummy auth token, so one is always provided, though I have never noticed any issues with connecting/editing despite the occasional warning popup. My guess is it's an issue with hot reloading, which would align with it being so difficult to reproduce, but that's purely speculative.

**Comment by jjgmckenzie** [comment]
@janthurau Had a look into it -- 
https://github.com/ueberdosis/hocuspocus/blob/main/packages/server/src/Hocuspocus.ts#L379 - The "unauthorized" code is used whenever an idle client times out; which might cause a developer to think that there is an issue. This is the only case where this code is returned when an error has not occurred.

There should probably be a separate code for idle timeout, so this console.warn does not occur. I'd make a PR (this should be a trivial fix) but there does not seem to be an accepted error code for idle timeouts.

Should there also potentially be a separate code for Errors? The unauthorized code is used seemingly as a "generic" code for errors, which seems inappropriate given the provider's console.warn does not align with that use at all

FWIW, Close due to internal server errors are generally 1011 (  https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent/code )

**Comment by raineorshine** [comment]
I am able to reproduce this in my staging environment, but not on localhost unfortunately. Maybe there is a websocket idle timeout on the hosting platform that Hocuspocus is not handling correctly.

@janthurau Is there something I can log that would be helpful to narrow down where this is coming from? It takes 2 min for me to deploy to my staging environment, so I can't iterate quickly, but maybe I can find something useful if you have a suggestion.

**Comment by jimmiebtlr** [comment]
Here's a full repo reproduction

https://github.com/jimmiebtlr/hocuspocus-repro-attempt

After starting frontend and backend, navigate to the /other route.  Wait 3 seconds (backend has timeout 3000), navigating to root then has the bad state without any auto recovery.

**Comment by jimmiebtlr** [comment]
It basically happens when the websocket provider is setup greater than the backends timeout prior to requesting a specific document.

**Comment by janthurau** [comment]
Thanks for this! Will check it out.

**Comment by janthurau** [comment]
ok, yea the issue is that the HocuspocusProviderWebsocket is opened much before the document provider actually connects. I think that's an easy fix.

@raineorshine I've sent you a friend request on Discord, if you can provide more details on how your setup looks like, maybe I can fix that issue as well (if it is not the same).

**Comment by jloganolson** [comment]
So i'm still seeing this issue:

> [HocuspocusProvider] An authentication token is required, but you didn’t send one. Try adding a `token` to your HocuspocusProvider configuration. Won’t try again.

But only on my node server (not web client) - the server is using the provider with HocuspocusProviderWebsocket
```
export const socket = new HocuspocusProviderWebsocket({
    WebSocketPolyfill: WebSocket, url: WS_URL
});

    const provider = new HocuspocusProvider({
        name: projectId,
        websocketProvider: socket,
        token: 'notoken' //necessary for the server to work
    });
```

Is there a workaround I should add? I'm using the most up to date release of hocuspocus (2.13.7)
