### ISSUE TITLE
Custom attributes gets removed when inserted from already designed template in to tiptap editor.

### ISSUE THREAD

**Issue by GSKarthik369** [ueberdosis/hocuspocus#567]
**Description**
I was trying to insert a pre-defined template which contains custom attributes for each elements based on the element needs like data-element-name are getting removed when inserted inside the tiptap editor. Also some of the html elements are also getting removed in the similar manner. 

How can we prevent the removal of these element attributes from being getting removed?

**Screenshot, video, or GIF**
1. Element structure which expected to be as when data is being inserted to tiptap editor.
![Download](https://user-images.githubusercontent.com/34792988/229073365-0c362930-4608-4213-870f-a1c264eecdc6.png)
2. Element structure when tiptap editor modifies it.
![image (1)](https://user-images.githubusercontent.com/34792988/229073502-0b77fc9d-8da0-4db7-9911-58178cd0df90.png)

Initial Content was inserted from the template by using content key in the configure content

**Comment by svenadlung** [comment]
Are you sure the issue is Hocuspocus related? It only occurs using collaboration with Hocuspocus?

**Comment by svenadlung** [comment]
Okay, just saw that you have opened an issue on Tiptap-side as well so I'll close here for now.
