### ISSUE TITLE
Multiplexing closes connection on auth failed

### ISSUE THREAD

**Issue by YousefED** [ueberdosis/hocuspocus#579]
**Description**
I'm using the same WS connection to connect to multiple documents.

For document A, I don't have access (I provide an invalid token)
For document B, I do have access.

As soon as I connect to document A, the websocket connection is closed.

**Expected behavior**
In a multiplexing environment where auth is document based, I'd expect the architecture to be completely independent. Anything I do with document A should be unrelated to what I do with document B and vice versa

**Comment by jinyang1994** [comment]
Is there any progress on the issue? @janthurau

**Comment by janthurau** [comment]
not yet - this was expected behavior for the multiplexing release. It definitely makes sense to change this though - we're always open for contributions :)
