### ISSUE TITLE
TiptapTransformer shows error while trying to set initial content from a template HTML to YDoc

### ISSUE THREAD

**Issue by binurajrvt** [ueberdosis/hocuspocus#581]
**Description**
As per this (https://tiptap.dev/hocuspocus/server/hooks#on-load-document) documentation, we can **create a Y.js document from JSON/HTML (once)** to set the initial content of the editor, which fetches an html template content from a Laravel API. It is for setting the initial content only once and after that, I am using RethinkDB for persistent storage using the Database Extension. But when I try to convert the html, it shows the error :
```
RangeError: Unknown node type: undefined
    at Schema.nodeType (file:///collab_server/node_modules/prosemirror-model/dist/index.js:2445:19)
    at Function.fromJSON (file:///collab_server/node_modules/prosemirror-model/dist/index.js:1522:23)
    at prosemirrorJSONToYDoc (file:///collab_server/node_modules/y-prosemirror/src/lib.js:251:20)
    at Prosemirror.toYdoc (file:///collab_server/node_modules/@hocuspocus/transformer/dist/hocuspocus-transformer.esm.js:2643:20)
    at Tiptap.toYdoc (file:///collab_server/node_modules/@hocuspocus/transformer/dist/hocuspocus-transformer.esm.js:2669:39)
    at fetchContent (file:///collab_server/server.rethink.js:49:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

   The sample html fetched from API is as simple as:
   ```
   <div>
       <h1>My First Heading</h1>
       <p>My first paragraph.</p>
  </div
```

The server configuration code part:

```
const server = Server.configure({
	 	async onLoadDocument(data) {
		const ydoc = fetchContent();
		return ydoc;
	}, 
	port: process.env.HOCUSPOCUS_PORT,
	extensions: [
		new Database({
			fetch: async ({ documentName }) => {
			...
			...
			...
```

fetchContent code:

```
async function fetchContent() {
	try {
		console.log("Fetching from API....");
		const response = await fetch(
			"http://webserver/api/template?room=Lqwvcz4"
		);
		const data = await response.json();
		const ydoc = TiptapTransformer.toYdoc(
			data.template_content,
			"default",
			[StarterKit]
		);
		return ydoc;
	} catch (error) {
		console.error(error);
	}
}
```

**Expected behavior**
Set the initial content from the html.

**Environment?**
 - operating system: MAC OS 12.1, Ubuntu
 - browser: Chrome, Firefox, Safari
 - mobile/desktop: Desktop
 - Hocuspocus version: 1.0.0-beta.2

**Comment by janthurau** [comment]
hey @binurajrvt, indeed our documentation is inaccurate here, thanks for this! Will fix it now.

You have to pass JSON to the transformer, so this should work for you:

```typescript

const html = `<div>
    <h1>My First Heading</h1>
    <p>My first paragraph.</p>
</div>`

new HocuspocusProvider({
  document: TiptapTransformer.toYdoc(
    generateJSON(html, [StarterKit]), // this is the important part
  ),
})

```

**Comment by binurajrvt** [comment]
So this has to be on client side where we initialise provider? I moved the transformation part from hocuspocus server code and added in client side like:

```
const html = `<div>
    <h1>My First Heading</h1>
    <p>My first paragraph.</p>
</div>`;

const ydoc = TiptapTransformer.toYdoc(
	generateJSON(html, [StarterKit]) // this is the important part
);

const initialiseSocket = (room) => {
	const websocketProvider = new HocuspocusProvider({
		document: ydoc,
		url: process.env.REACT_APP_HOCUSPOCUS_WS_URL,
		parameters: {
			key: "321456987",
		},
		name: room,
	});
	return websocketProvider;
};

const websocketProvider = initialiseSocket(room));
```

But now content is duplicated several times when we open the editor.  Should this be used on the client side or server side `Server.configure` on `onLoadDocument` ? How to do that only once for initial setting? I am using rethink db on server side for persistence with Database extension as mentioned above.
