### ISSUE TITLE
TiptapTransformer initial content html in ydoc duplicates. 

### ISSUE THREAD

**Issue by binurajrvt** [ueberdosis/hocuspocus#592]
**Description**
This is based on the bug report: https://github.com/ueberdosis/hocuspocus/issues/581

**Steps to reproduce the bug**
As given in this (https://github.com/ueberdosis/hocuspocus/issues/581#issuecomment-1516829791) suggestion, moved the server side initial setting to client side, where the Provider is configured.

```
const html = `<div>
    <h1>My First Heading</h1>
    <p>My first paragraph.</p>
</div>`;

const ydoc = TiptapTransformer.toYdoc(
	generateJSON(html, [StarterKit]) // this is the important part
);

const initialiseSocket = (room) => {
	const websocketProvider = new HocuspocusProvider({
		document: ydoc,
		url: process.env.REACT_APP_HOCUSPOCUS_WS_URL,
		parameters: {
			key: "321456987",
		},
		name: room,
	});
	return websocketProvider;
};

const websocketProvider = initialiseSocket(room));
```

But now content is duplicated several times when we reload the page. How to ensure this is done only once for initialising content, even if page is reloaded?  Should this be used on the client side or server side `Server.configure` on `onLoadDocument` ?  I am using rethink db on server side for persistence with Database extension on server side.

**Screenshot, video, or GIF**
<img width="410" alt="Screenshot 2023-04-27 at 11 11 14 AM" src="https://user-images.githubusercontent.com/106507805/234769513-2cf0437a-b6d7-4255-a124-853f8a4d401d.png">

**Expected behavior**
Set the initial content from the html only once even if page is refreshed.

**Environment?**
 - operating system: MAC OS 12.1, Ubuntu
 - browser: Chrome, Firefox, Safari
 - mobile/desktop: Desktop
 - Hocuspocus version: 1.0.0-beta.2

**Comment by janthurau** [comment]
@binurajrvt you can't initialize the ydoc from json multiple times, so you have to check if the ydoc already exists or not, and only if it doesn't exist populate it from JSON using the transformer.
