### ISSUE TITLE
TiptapTransformer initial content setting removes all <img> and <table> tags

### ISSUE THREAD

**Issue by AnnieTJohn** [ueberdosis/hocuspocus#598]
**Description**
At hocuspocus server side, we fetch the initial content as html from an external API, converts it to ydoc:

```
const server = Server.configure({
    async onLoadDocument(data) {
        const ydoc = await fetchInitialDocument(data.documentName);
        return ydoc;
    },
    port: process.env.HOCUSPOCUS_PORT,
    extensions: [
        new Database({
       ...
       ...
       ...
```

In fetchInitialDocument(documentName) function, we fetch the html, if the ydoc does not already exist, then convert the fetched html like:
```
     ....
     ....
     const ydoc = TiptapTransformer.toYdoc(
	   generateJSON(templateHtml, [StarterKit])
    );
    return ydoc;
```

This is done only once, if the ydoc does not exist in our RethinkDB database which is used for persistent storage using the @hocuspocus/extension-database. Everything works fine, but the problem is that, the TiptapTransformer removes all <img> and <table> tags irrespective of whether it is enclosed in <p> tag or not.

**Expected behavior**
The initial content should be set as seen in the orginal template html.

**Screenshot, video, or GIF**

![ss1](https://user-images.githubusercontent.com/129515029/236222042-ef5bee05-73a7-40d3-81b9-b78c59e5c556.png)

![ss2](https://user-images.githubusercontent.com/129515029/236222189-66efb161-5bf5-4a77-87e0-da19e3eba48f.png)

When initial content is set in the editor, when inspected, it is as follows.

![ss3](https://user-images.githubusercontent.com/129515029/236223249-c400cc09-e57e-4253-8b90-d9529db0d2a6.png)

**Environment?**
 - operating system: MAC OS 12.1, Ubuntu
 - browser: Firefox, Chrome
 - mobile/desktop: Desktop
 - Hocuspocus version:  1.0.0-beta.2

**Comment by janthurau** [comment]
hey @AnnieTJohn I can't reproduce this.

I tried this (from https://tiptap.dev/api/nodes/image) and it works, please provider more information if you still experience the same issue.

```typescript
const doc = TiptapTransformer.toYdoc(
  {
    type: 'doc',
    from: 0,
    to: 71,
    content: [
      {
        type: 'paragraph',
        from: 0,
        to: 67,
        content: [
          {
            type: 'text',
            from: 1,
            to: 66,
            text: 'This is a basic example of implementing images. Drag to re-order.',
          },
        ],
      },
      {
        type: 'image',
        from: 67,
        to: 68,
        attrs: {
          src: 'https://source.unsplash.com/8xznAGy4HcY/800x400',
          alt: null,
          title: null,
        },
      },
      {
        type: 'image',
        from: 68,
        to: 69,
        attrs: {
          src: 'https://source.unsplash.com/K9QHL52rE2k/800x400',
          alt: null,
          title: null,
        },
      },
    ],
  }, 'default', [StarterKit, Image.configure({
    inline: true,
  })],
)
```

**Comment by AnnieTJohn** [comment]
Thanks for the suggestion. But now we get an error: `RangeError: Unknown node type: image`

The conversion part is:

```
...
...
import Image from "@tiptap/extension-image";
...
...


const template_json = generateJSON(template_html, [
				StarterKit,
				Image.configure({
					inline: true,
				}),
			]);
```

The generated json is:
```
{
	"type": "doc",
	"content": [{
		"type": "paragraph",
		"content": [{
			"type": "text",
			"text": "Image DOCX"
		}]
	}, {
		"type": "paragraph",
		"content": [{
			"type": "image",
			"attrs": {
				"src": "http://localhost:8090/documents/NEW-10/media/image1.png",
				"alt": null,
				"title": null
			}
		}]
	}]
}

const ydoc = TiptapTransformer.toYdoc(template_json);
```

But we get the error:

```
RangeError: Unknown node type: image
    at Schema.nodeType (file:///rvrite_server/node_modules/prosemirror-model/dist/index.js:2445:19)
    at Function.fromJSON (file:///rvrite_server/node_modules/prosemirror-model/dist/index.js:1522:23)
    at Schema.nodeFromJSON (file:///rvrite_server/node_modules/prosemirror-model/dist/index.js:2430:21)
    at Array.map (<anonymous>)
    at Function.fromJSON (file:///rvrite_server/node_modules/prosemirror-model/dist/index.js:319:35)
    at Function.fromJSON (file:///rvrite_server/node_modules/prosemirror-model/dist/index.js:1521:32)
    at Schema.nodeFromJSON (file:///rvrite_server/node_modules/prosemirror-model/dist/index.js:2430:21)
    at Array.map (<anonymous>)
    at Function.fromJSON (file:///rvrite_server/node_modules/prosemirror-model/dist/index.js:319:35)
    at Function.fromJSON (file:///rvrite_server/node_modules/prosemirror-model/dist/index.js:1521:32)
    at prosemirrorJSONToYDoc (file:///rvrite_server/node_modules/y-prosemirror/src/lib.js:251:20)
    at Prosemirror.toYdoc (file:///rvrite_server/node_modules/@hocuspocus/transformer/dist/hocuspocus-transformer.esm.js:2643:20)
    at Tiptap.toYdoc (file:///rvrite_server/node_modules/@hocuspocus/transformer/dist/hocuspocus-transformer.esm.js:2669:39)
    ```

**Comment by janthurau** [comment]
You need to pass the Image extension to the `toYdoc` function

**Comment by AnnieTJohn** [comment]
Thank you... that worked. That means we need to pass the image extension to `generateJSON` and `toYdoc`?  Like:

```
const ydoc = TiptapTransformer.toYdoc(
				generateJSON(data.template_content, [
					StarterKit,
					Image.configure({
						inline: true,
					}),
				]),
				"default",
				[
					StarterKit,
					Image.configure({
						inline: true,
					}),
				]
			);
```

**Comment by AnnieTJohn** [comment]
@janthurau one more thing, I need to implement custom extension for display image to the `toYdoc` function. And i copied the custom extension file to the hocuspocus server side (enclosed in extension folder) and tried to import but got some errors

`Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/rvrite_server/extensions/DisplayFig' imported from /rvrite_server/server.rethink.js
`
