### ISSUE TITLE
Type "onStoreDocumentPayload" does not have expected optional variable 'update'

### ISSUE THREAD

**Issue by jjgmckenzie** [ueberdosis/hocuspocus#599]
The type "onStoreDocumentPayload", defined in [types.ts#240]( https://github.com/ueberdosis/hocuspocus/blob/54d810e975e9699d9ae2a75444d55c48e21d0a6a/packages/server/src/types.ts#L240) does not have the variable 'updates', as referenced in [the documentation](https://tiptap.dev/hocuspocus/server/hooks#on-store-document)

This variable should exist as an optional Uint8Array, as not all calls to store the document come with updates.

**Comment by jjgmckenzie** [comment]
I would have made a PR for this, but was unsure if the change should be to the documentation if this is left deliberately abstracted or the type

**Comment by janthurau** [comment]
Thanks @jjgmckenzie! `onStoreDocument` is debounced, so there is no single `update`, it can be multiple ones. If you want to subscribe to all updates, you can use the `onChange` hook.

I've updated the docs, thx again!

**Comment by chenyuncai** [comment]
it seemd the debounced onStoreDocument hook just for save whole doc to database but not a delta(s)

maybe it should have a 'update list' so them can be inserted  whthout so many database inertactions but one for a while
