### ISSUE TITLE
How to pass Hocuspocus errors to front end?

### ISSUE THREAD

**Issue by AnnieTJohn** [ueberdosis/hocuspocus#605]
**Description**

I am using TipTap with Hocuspocus for collaborative editing, with Database extension, Transformer to convert initial content html from an API to ydoc onLoadDocument (once) then ydoc is synced to RethinkDB for persistent storage. I am using ReactJS as frontend of the editor. Everything working fine with your excellent support and help. But I couldn't find a way to pass if some error occurs on server.js, like API fetching errors, invalid format so on. I would like to send the error to the front end React. How is this possible so that I can show something like 'Failed to fetch template html' for example.

**Expected behavior**
Pass the errors to front end

**Environment?**
 - operating system: MAC OS 12.1, Ubuntu
 - browser: Firefox, Chrome
 - mobile/desktop: Desktop
 - Hocuspocus version: 1.0.0-beta.2

**Comment by janthurau** [comment]
@AnnieTJohn please check out Discord for question on how to do something, Github is just for tracking bugs :) The community is much bigger in Discord.

Anyway, you can potentially solve this using `connection.sendStateless`.

**Comment by AnnieTJohn** [comment]
Thank you so much for the suggestion.
