### ISSUE TITLE
Proper Documentation for Multiplexing

### ISSUE THREAD

**Issue by develink** [ueberdosis/hocuspocus#611]
Multiplexing needs a little bit more documentation.

I've connected HocusPocusProvider using HocuspocusProviderWebsocket perfectly. And now all my documents is using a single websocket, rather than a new websocket for each document. But I am facing two issues here:

1. How to disconnect the provider on leaving the document? Because if I will call myProvider.disconnect() it disconnects the websocket as well. and myProvider.close() or setting myProvider as null doesn't update the awareness at all.
2. Document connects and everything works just fine but after some time I receive [HocuspocusProvider] An authentication token is required, but you didn’t send one. Try adding a `token` to your HocuspocusProvider configuration. Won’t try again.
Although I am providing sending the token. I've even tried removing the whole Authentication Check on Server side as well. My guess is that it has something to do with Point 1. Because the provider for the previous document isn't closing properly, but I am not sure.

Can you provide some help on this ASAP. Thanks

**Comment by janthurau** [comment]
@develink if you want to disconnect the provider without disconnecting the socket, you can call provider.terminate (HocuspocusProvider, not HocuspocusProviderWebsocket).

About your second point, there's an issue about it here: #566

**Comment by akashbit** [comment]
hi @janthurau thanks for the reply. But there is no function terminate for HocuspocusProvider. I looked into the code also of HocuspocusProvider.

**Comment by develink** [comment]
hi @janthurau Thanks for the reply. Unfortunately there is no method as such called terminate for the HocusPocusProvider. I've searched in the github repository code as well for the Provider. Am I missing something here?

**Comment by janthurau** [comment]
Ah sorry, I meant destroy 🤦‍♀️

**Comment by akashbit** [comment]
But destroy actually disconnects the websocket as well. I want to retain the websocket connected but provider disconnected. So that I can open another document on the same websocket connection again.

**Comment by develink** [comment]
But destroy actually disconnects the websocket as well. I want to retain the websocket connected but provider disconnected. So that I can open another document on the same websocket connection again.

**Comment by janthurau** [comment]
Ah, yea that doesn't work atm because the server will close the connection once the last document was closed.

So you can either first open the new provider and then destroy the old one, or you create a patch that adds some kind of delay before the server closes the connection (or you wait until someone adds it :))

**Comment by develink** [comment]
That's a bump. 2.0 actually created more issues rather than solving anything. Guess I have to go back to 1.0, at least that was somewhat working.
