### ISSUE TITLE
Failed to resolve entry for package "@hocuspocus/provider".

### ISSUE THREAD

**Issue by scenaristeur** [ueberdosis/hocuspocus#630]
**Description**
 i great job, , i've already used hocuspocus on https://github.com/scenaristeur/tiptap-yjs
https://scenaristeur.github.io/tiptap-yjs/
but here trying to test the playground, i've got an error : 

just git pull and npm install, npm run start missing a link or something ?

```
[plugin:vite:import-analysis] Failed to resolve entry for package "@hocuspocus/provider". The package may have incorrect main/module/exports specified in its package.json.

/home/smag/dev/hocuspocus/playground/frontend/src/pages/Index.vue
```

same with node v16.19.0 or v18.16.0 on linux mint

![Screenshot 2023-06-15 at 19-17-58 Vite App](https://github.com/ueberdosis/hocuspocus/assets/4020744/65881fd7-d98d-43ec-9adf-71fbcff556b2)

**Comment by janthurau** [comment]
hey @scenaristeur, thanks for the report! Indeed we were missing instructions for this. You need to run `npm run build` in the repo root to build the packages first.

I've just pushed a change to add this to the README.

**Comment by scenaristeur** [comment]
thxs ;-)
