### ISSUE TITLE
Server doesn't export DirectConnection

### ISSUE THREAD

**Issue by canadaduane** [ueberdosis/hocuspocus#632]
**Description**
The `server` package does not export the new `DirectConnection` class type.

**Steps to reproduce the bug**
```
import { DirectConnection } from "@hocuspocus/server"
```

**Expected behavior**
The type should be available, in cases where you want to be able to pass around the connection object.

**Additional context**
I forgot to add it to the index.ts file when I made the PR for DirectConnection.

**Comment by janthurau** [comment]
makes sense! I've just aded the typings 🥳

**Comment by shincurry** [comment]
`DirectConnection` **class** is still not exported in `index.ts` file.

Currently in 2.7.1:

```ts
import { DirectConnection } from "@hocuspocus/server"

// this is actual DirectConnectionInterface, not the DirectConnection class
```

if using in Node.js TypeScript `"module": "commonjs"`, there is a workaround, we can directly import from `DirectConnection.ts` file
```
import { DirectConnection } from '@hocuspocus/server/dist/packages/server/src/DirectConnection';
```
But in Node.js TypeScript `"module": "NodeNext"`, there is no way to import `DirectConnection` **class** type.

#### How to fix:

* rename `DirectConnection` to `DirectConnectionInterface` in `types.ts` file
* Add `export * from './DirectConnection.js'` into `index.ts` file

these changes can both export DirectConnection **class** and **interface** types.
