### ISSUE TITLE
What's the best way to edit the document server-side?

### ISSUE THREAD

**Issue by linspw** [ueberdosis/hocuspocus#634]
**The problem I am facing**
I'm needing to handle document-side changes when it's live on the hocuspocus server.
However, when changed by the server, it does not trigger the save document events.

**The solution I would like**
I don't know the best way, but there could be some way to make clearer edits to the ydoc on the server side so that it triggers the main events.

**Alternatives I have considered**
I'm getting the document directly from the "documents" property of the server
![image](https://github.com/ueberdosis/hocuspocus/assets/43552865/33a9cf85-c19c-4dc7-9707-4748065f635e)

**Comment by janthurau** [comment]
hey @linspw, we have a `DirectConnection` in Hocuspocus (I'm working on the documentation for this), but it can already be used: https://github.com/ueberdosis/hocuspocus/pull/610

Let me know if that helps 🙏

**Comment by linspw** [comment]
Thank you very much for this here too @janthurau , it will help a lot!
