### ISSUE TITLE
Nextjs - Firefox can’t establish a connection to the server at ws://127.0.0.1:1234/

### ISSUE THREAD

**Issue by pierrelouisdelx** [ueberdosis/hocuspocus#639]
**Description**
Hi,
there is an issue using slate-yjs in next@13.4.6.
When I try to connect with HocusPocusProvider to my hocus-pocus server the socket connects and disconnects immediately. The connection reach the server but somehow the socket hangs up.

The problem is that for the same code, it's working without any problem with vite but not on nextjs.

Here is the code that I've used: https://github.com/pierrelouisdelx/slate-yjs-next

**Steps to reproduce the bug**
```import { HocuspocusProvider } from '@hocuspocus/provider'
import React, {
    useEffect,
    useMemo,
   useState
} from 'react'

const [connected, setConnected] = useState(false)

const provider = useMemo(
        () =>
            new HocuspocusProvider({
                url: HOCUSPOCUS_ENDPOINT,
                name: 'slate-yjs-demo',
                onConnect: () => setConnected(true),
                onDisconnect: () => setConnected(false),
            }),
        []
    )

    useEffect(() => {
        if (typeof window !== 'undefined') {
            provider.connect()
        }
        console.log(provider)
    }, [])```

**Expected behavior**
Connect to the hocuspocus server

**Environment?**
Firefox 114.0.1 (64-bit), Chrome 114.0.5735.133 (Official Build)

**Comment by Geod-exe** [comment]
I have the same probleme with NextJS 13 too, tiptap editor and Firefox/chromium/opera....
![Screenshot_2023-06-28_15-39-27](https://github.com/ueberdosis/hocuspocus/assets/79382688/e6a83144-a06b-44eb-bea0-7d4610706fa1)

**Comment by janthurau** [comment]
Hi!

I've just created a simple repository showing nextjs, tiptap & hocuspocus up and running, without any of the mentioned issues. Let me know if that helps. Somehow it's a bit weird (for a non-react/nextjs-user like me) to make sure the provider really only connects on the client, but it does work for me.

https://github.com/janthurau/tiptap-hocuspocus-nextjs
