### ISSUE TITLE
Release to fix bugs introduced since 2.0.4/2.0.5

### ISSUE THREAD

**Issue by georeith** [ueberdosis/hocuspocus#644]
Not a new bug report just letting you know we're stuck on HP 2.0.3 currently because 2.0.4 or 2.0.5 introduced a breakage in our application.

The refactor in 2.2.0 _appears_ to resolve that part of the issue but introduced its own critical bug that was fixed here: https://github.com/ueberdosis/hocuspocus/pull/641 

This completely broke our application because we are relying on the information from `onDisconnect` to manage our load balancing across worker processes which now track documents closing as `undefined`.

Would really appreciate a new release with the latest fixes as we have some work blocked as it needs changes introduced in 2.1.0 but don't have a working version of HP for our application since 2.0.3 (maybe 2.0.4).

**Comment by janthurau** [comment]
ahrg, sorry for this! New release will be out this evening.

**Comment by georeith** [comment]
Thanks @janthurau

**Comment by martinboksa** [comment]
@georeith I used `yarn patch` as the perfect workaround until release becomes available.

**Comment by georeith** [comment]
> @georeith I used `yarn patch` as the perfect workaround until release becomes available. Maybe it can help :)

Good shout 👍

**Comment by janthurau** [comment]
v2.2.1 is now available - let me know if you experience any further issues.

https://github.com/ueberdosis/hocuspocus/releases/tag/v2.2.1
