### ISSUE TITLE
Provider is not retrying authentiation when token is invalid.

### ISSUE THREAD

**Issue by manoelneto** [ueberdosis/hocuspocus#676]
**Description**
Provider is not retrying authentiation when token is invalid.

**Steps to reproduce the bug**

The best way to see this is to create a provider where the token is a function that returns a promise. inside the function I have a request to generate a new token. If the token is invalid, I expect to retry refreshing the token again, but that never happen.

Our implementation sets the token validity for only 30 seconds, so they can become invalid very easily, just user losing their internet connection for some time, and hocuspocus will try to create a new connection with the server, but at this point the token is not valid anymore.

```
const provider = new HocuspocusProvider({
  ...,
  token: async () => {
    return axios.get(...)
  },
})
```

Also, passing the quiet: true to the provider didn't really set the quiet in the HocuspocusProviderWebsocket for some reason, and I'm still getting the log.

**Expected behavior**
Provider trying to reconnect

**Screenshot, video, or GIF**

Just a disclaimer: In the onAuthenticationFailed, I expect to add a code to refresh the token again. And if the provider tries again to connect, I would use that new token in the next retry.

https://www.loom.com/share/70ca5444391a46af83eafeb02f183a65

**Environment?**
 - operating system: Mac Os
 - browser: Chrome
 - mobile/desktop: Desktop
 - Hocuspocus version: `"@hocuspocus/provider": "^2.1.0",`

**Additional context**
I guess the problem is on this line https://github.com/ueberdosis/hocuspocus/blob/main/packages/provider/src/HocuspocusProviderWebsocket.ts#L459

If the server is not in quiet mode, it's logging that message and stop the execution, which I think is wrong. I wonder why there is such a "TODO remove me" there.

**Comment by janthurau** [comment]
hmm, that's a feature :-D

Can you work around that using the onAuthenticateFailed hook? You can probably check the error message, change the token, and then call provider.connect() 🤔

**Comment by sumbad** [comment]
Hi @janthurau! Can you please give more information about reconnection using the onAuthenticateFailed hook? 

I tried to call provider.connect() inside the onAuthenticateFailed hook, but after some digging realized that the system takes some time to close a connection, and it can lead to asynchronous problems. So that, we should call provider.connect() inside the onDisconnect or onClose hooks after updating a token inside onAuthenticateFailed. Is it right?
