### ISSUE TITLE
It should be possible to publish a doc content change even when there are openConnections on the doc

### ISSUE THREAD

**Issue by martin-cycle** [ueberdosis/hocuspocus#680]
**The problem I am facing**
When a socket is open on my yDoc, I cannot modify its content while using `openDirectConnection`. I see the hooks being triggered and when there are no open socket on the doc, the modifications are correctly made but when a connection is open, the changes don't apply.

**The solution I would like**
A simple way to modify a RT description even when a socket is already open.

**Alternatives I have considered**
I built a custom way to modify the content by publishing my modifications through redis. The redis extension then takes care of modifying the doc content if it's open.
```
pubsub
        .getPublisher()
        .publishBuffer(
          `hocuspocus:${generateIDFromDomain(doc, {}, {})}:host-${uuid()}`,
          Buffer.from(generateUint8ArrayMessage(newRTDescription, generateIDFromDomain(doc, {}, {}))),
        );
```

How I tried (unsuccessfully) to do with the `openDirectConnection`:
```
serverRt.openDirectConnection(`sync/doc/${generateIDFromDomain(doc, {}, {})}`, { viewer })
        .then(c => { 
          c.transact(d => Yjs.applyUpdate(d, Buffer.from(convertJSONToBinary(JSON.stringify(newRTDescription)), 'base64'))); 
          c.disconnect(); 
        })
```

I think it should be possible maybe by splitting my transaction into smaller chunks but it looked a bit over-engineered to convert my whole json into granular changes. Hopefully the upcoming documentation should give more informations with builtin examples but so far I had to keep my in-house solution.

**Additional context**
I am using Hocuspocus for RT collaboration on Tiptap editor with redis and database extensions.
If what I'm expecting is not the intended use of `openDirectConnection`, I'd be happy to open a PR with my utilities function.

**Comment by janthurau** [comment]
hmm, that's weird - that should definitely work.

Not sure though what your methods (generateUint8ArrayMessage, convertJSONToBinary) are doing. You should also pass the Uint8Array to Y.applyUpdate, so I'm not sure why you pass the uint8array in the first snippet, but some "Binary" in the directconnection?

Does it work if you do it like this?

`c.transact(d => Y.applyUpdate(generateUint8ArrayMessage(newRTDescription, generateIDFromDomain(doc, {}, {})`

**Comment by martin-cycle** [comment]
I adapted my transact logic like so: `c.transact(d => Yjs.applyUpdate(d, convertJSONToUint8Array(newRTDescription)))`
where convertJSONToUint8Array is the following:
```
export const convertJSONToUint8Array = (contentJSON: JSONContent): Uint8Array => {
  const schema = getSchema(extensions as Extensions);
  const docInit = prosemirrorJSONToYDoc(schema, contentJSON, 'sharedDoc');
  const update = Yjs.encodeStateAsUpdate(docInit);
  return update;
};
```
But I'm stuck with the same issue, it doesn't work when a socket is open on the doc.

**Comment by janthurau** [comment]
hmm, weird. I've just set up two quick test cases for this, but haven't been able to reproduce an issue:

```
test('direct connection works even if provider is connected', async t => {
  await new Promise(async resolve => {
    const server = await newHocuspocus()

    const provider = newHocuspocusProvider(server, {
      onSynced() {
        provider.document.getMap('config').set('a', 'valueFromProvider')
      },
    })

    await sleep(100)

    const directConnection = await server.openDirectConnection('hocuspocus-test')
    await directConnection.transact(doc => {
      t.is('valueFromProvider', String(doc.getMap('config').get('a')))
      doc.getMap('config').set('b', 'valueFromServerDirectConnection')
    })

    await sleep(100)
    t.is('valueFromServerDirectConnection', String(provider.document.getMap('config').get('b')))

    console.log(provider.document.getMap('config').get('b'))
    resolve(1)
    t.pass()
  })
})

test('direct connection can apply yjsUpdate', async t => {
  await new Promise(async resolve => {
    const server = await newHocuspocus()

    const provider = newHocuspocusProvider(server)

    t.is('', provider.document.getXmlFragment('default').toJSON())

    const directConnection = await server.openDirectConnection('hocuspocus-test')
    await directConnection.transact(doc => {
      Y.applyUpdate(doc, Y.encodeStateAsUpdate(TiptapTransformer.toYdoc({
        type: 'doc',
        content: [
          {
            type: 'paragraph',
            content: [
              {
                type: 'text',
                text: 'Example Paragraph',
              },
            ],
          },
        ],
      })))
    })

    await sleep(100)

    t.is('<paragraph>Example Paragraph</paragraph>', provider.document.getXmlFragment('default').toJSON())

    resolve(1)
    t.pass()
  })
})
```

**Comment by martin-cycle** [comment]
I finally made it work thanks your help ! 🔥
I needed to specify the field which is a "sharedDoc" in our case. And using the TiptapTransformer instead of my custom utils functions helped a lot as well. Here is my final solution:

```
serverRt.openDirectConnection(generateIDFromDomain(doc, {}, {}), { viewer })
      .then(c => { 
        c.transact(d => Yjs.applyUpdate(d, Yjs.encodeStateAsUpdate(TiptapTransformer.toYdoc(newRTDescription, "sharedDoc", extensions as Extensions)))); 
        c.disconnect(); 
      })
```

It's working for doc with our without an open connection 👌

Thanks again for your time 🙏
