### ISSUE TITLE
How can a provider know if the document existed or not

### ISSUE THREAD

**Issue by maitre-piccolo** [ueberdosis/hocuspocus#691]
So I want my editor (Tiptap)  to load a default content if the requested document doesn't exist on the  HocusPocus server. If it does exist, then I want the editor to load the document from the server.

Maybe I'm trying to do things the wrong way, but right now it's doing both at the same time, and I can't find a way to prevent this.

For example each time I load a tiptap editor with local content, this local content is added to the linked Y document.
If I set up an editor with "<p>Hello there.</p>" as content, it works fine.
But if I set up this editor again, with the same ID (document name), then the content of the editor will be "<p>Hello there.</p><p>Hello there.</p>" instead of just "<p>Hello there.</p>".

I tried [all the provider events
](https://tiptap.dev/hocuspocus/provider/events) but couldn't find a way for the provider to know if the document existed on the server or not. Basically if the data from the server was empty or not during the first sync.

Whether the document existed or not, all the events output are the same, except onMessage, but couldn't find a reliable way to leverage onMessage. 

Thanks for the help.

**Comment by janthurau** [comment]
hey @maitre-piccolo, the best way is to add this handling to the onLoadDocument hook (so server-side) and pre-fill the document with the desired initial content if it didn't exist.

If you want to do this on the frontend side, you can probably send a stateless message in onLoadDocument (connection.sendStateless) and inform the provider (subscribe using `onStateless` provider hook).
