### ISSUE TITLE
onConnect payload includes `context` but type signature does not reveal it

### ISSUE THREAD

**Issue by canadaduane** [ueberdosis/hocuspocus#699]
**Description**

The `onConnect` hook includes `context`, but the type signature does not admit to it :)

<img width="837" alt="image" src="https://github.com/ueberdosis/hocuspocus/assets/129/dab48b0d-b304-44e4-94c8-86943e8a5a22">

https://github.com/ueberdosis/hocuspocus/blob/main/packages/server/src/ClientConnection.ts#L332

**Steps to reproduce the bug**
When an extension has an `onConnect` hook, it can't access the context.

**Expected behavior**
Extensions should have access if it is provided in the payload.

<img width="454" alt="image" src="https://github.com/ueberdosis/hocuspocus/assets/129/c9f6aabe-d168-4539-8e38-0baacf06d161">

**Comment by janthurau** [comment]
true, thx! I've just added it.
