### ISSUE TITLE
onRequest hook should allow to write custom status and response

### ISSUE THREAD

**Issue by aonnikov** [ueberdosis/hocuspocus#708]
**The context**
I'm happy to see onRequest hook feature in Hocuspocus, it allows me to extend collaboration server with a tiny REST server that can perform some utility operations without starting http + ws server manually.

**The problem**
Currently, onRequest hook does not allow to return anything except 200 OK without payload. Sometimes I would want to return some payload, or another HTTP code. In other words, the hook should decide what to return to the client. It would also allowed to avoid potential problem when the server tries to write response that has already been ended. As I figured out, this leads to the sever crash 😞 

**How to solve it**
Probably the easiest way would be to check whether the response is ended before trying to write it in the Server. This change would allow to use something like express.js for routing within onRequest hook and it would help to avoid request/response handling boilerplate.

**Comment by janthurau** [comment]
@aonnikov you can just reject the promise, that will cause the server to do nothing, so I think what you want to achieve is already possible (see https://tiptap.dev/hocuspocus/server/hooks#on-request) :)
