### ISSUE TITLE
Connection getting closed with "Unauthorized" in Firefox and Safari after about 30 seconds

### ISSUE THREAD

**Issue by drewag** [ueberdosis/hocuspocus#716]
When running in Firefox or Safari, the connection gets closed after about 30 seconds with `event.reason = "Unauhtorized"` causing the warning: `[HocuspocusProvider] An authentication token is required, but you didn’t send one. Try adding a `token` to your HocuspocusProvider configuration. Won’t try again.'`

I do have a token configured, I've confirmed that messages are being sent regularly so it isn't that the connection is being closed for inactivity, and the connection works ok in Arc/Chrome.

Only hint of a problem I see is that when the token message is sent when opening the connection, the backend prints `Unable to handle message of type 2: no handler defined!`. But it does that for Arc/Chrome as well.

The token I'm using is "insufficient-secret" because I just want to trigger the onAuthenticate handler where I then validate the authentication through a cookie.

I've also confirmed that onAuthenticate is not being called again before closing. It seems to close in the browser, not from the backend.

**Comment by drewag** [comment]
The backend doesn't call on onDisconnect or onDestroy

**Comment by janthurau** [comment]
hmm, can you share the code that you use to create the provider / socket? I cannot reproduce this, and the warning "Unable to handle message of type 2" looks like something isn't connecting property, as this means that an authenticated connection received the auth message.

**Comment by drewag** [comment]
Here is how I'm creating the server:

```
    this.server = Server.configure({
      port: 8001,
      extensions: [new Logger(), this.docStore.generateExtension()],
      // timeout: 10000,
      // onAuthenticate: this.onAuthenticate,
      onLoadDocument: this.generateLoadDocumentHandler(),
      onDisconnect: this.onDisconnect,
    });
```

And actually, I realized it is directly related to the timeout on the server side. The connection is closed right when at the timeout, regardless of what I set it to (10 seconds or multiple minutes). So it seems like `clearTimeout` is not being called for some reason.

**Comment by drewag** [comment]
Sorry, I updated to the latest version of HocusPocus and this problem no longer exists.

For future reference, it was happening on all browsers, it was just more prevalent on Firefox and Safari. It seemed to be a race condition where the frontend was listening to the wrong websocket (a socket it never sent any messages over where it was instead sending it over another).
