### ISSUE TITLE
Server has websocket.binarytype set to arraybuffer, not nodebuffer

### ISSUE THREAD

**Issue by akwirick** [ueberdosis/hocuspocus#718]
I saw an issue on my logs where the `ws` library was complaining about a type mismatch when emitting messages.   Confirmed that patching the websocket binarytype to `nodebuffer`  fixes the underlying issues.   Basically, since `ws` is both a browser and node library, we're inadvertently opting in to browser behavior on the server and that's no bueno.

See https://github.com/ueberdosis/hocuspocus/blob/f584cb732d045cd615d0babad16503e6a7903312/packages/server/src/Connection.ts#L68  for the line to fix.

I can probably put together a PR next week, but it's Friday night local time and I'm not gonna get to it til after the weekend.

**Comment by janthurau** [comment]
@akwirick Can you share the log / error that you were seeing? Which node version do you use?
Havent seen any issues related to this, and I actually have zero idea what that changes means. I just put together a PR and will check now what tests say, but not sure what that is doing :)

**Comment by akwirick** [comment]
Here's a snippet from my logs when the binarytype is set to `arraybuffer`
```
{"level":50,"time":1696907675863,"pid":20597,"hostname":"Bear","err":{"type":"TypeError","message":"The \"chunk\" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of ArrayBuffer","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The \"chunk\" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of ArrayBuffer\n    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)\n    at new NodeError (node:internal/errors:405:5)\n    at readableAddChunk (node:internal/streams/readable:285:13)\n    at Readable.push (node:internal/streams/readable:253:10)\n    at WebSocket.message (/home/awirick/src/ai-platform/node_modules/.pnpm/ws@8.14.2/node_modules/ws/lib/stream.js:64:17)\n    at WebSocket.emit (node:events:526:35)\n    at Receiver.receiverOnMessage (/home/awirick/src/ai-platform/node_modules/.pnpm/ws@8.14.2/node_modules/ws/lib/websocket.js:1192:20)\n    at Receiver.emit (node:events:514:28)\n    at Receiver.dataMessage (/home/awirick/src/ai-platform/node_modules/.pnpm/ws@8.14.2/node_modules/ws/lib/receiver.js:545:14)\n    at Receiver.getData (/home/awirick/src/ai-platform/node_modules/.pnpm/ws@8.14.2/node_modules/ws/lib/receiver.js:478:17)\n    at Receiver.startLoop (/home/awirick/src/ai-platform/node_modules/.pnpm/ws@8.14.2/node_modules/ws/lib/receiver.js:167:22)\n    at Receiver._write (/home/awirick/src/ai-platform/node_modules/.pnpm/ws@8.14.2/node_modules/ws/lib/receiver.js:93:10)\n    at writeOrBuffer (node:internal/streams/writable:399:12)\n    at _write (node:internal/streams/writable:340:10)\n    at Writable.write (node:internal/streams/writable:344:10)\n    at Socket.socketOnData (/home/awirick/src/ai-platform/node_modules/.pnpm/ws@8.14.2/node_modules/ws/lib/websocket.js:1286:35)\n    at Socket.emit (node:events:514:28)\n    at addChunk (node:internal/streams/readable:343:12)\n    at readableAddChunk (node:internal/streams/readable:316:9)\n    at Readable.push (node:internal/streams/readable:253:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","code":"ERR_INVALID_ARG_TYPE"},"msg":"The \"chunk\" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of ArrayBuffer"}
```

Basically, the `ws` library is expecting a Buffer or Uint8Array but is receiving the ArrayBuffer.   Theoretically, it _should_ be possible to get ArrayBuffer's to work as well but it really doesn't make sense to _not_ use either `nodebuffer` or `fragment` if we are running in a Node environment.

**Comment by akwirick** [comment]
For more context, this is running on a fastify server operating in http1.1 mode.   Everything else seems to work fine there, just this one little unexpected type issue.

**Comment by janthurau** [comment]
ah, this probably happened because you are using ws@^8 already, while we were still at ^7. Just weird that I didn't see this, because I actually upgraded this week 🤔 anyway, will merge it. thx!
