### ISSUE TITLE
Content inserted one time per connection

### ISSUE THREAD

**Issue by MrBisp** [ueberdosis/hocuspocus#725]
**Description**
When connecting to HocusPocus using the following code, the content is inserted into the page once per connection.

```
const ydoc = TiptapTransformer.toYdoc(
      json,
      "default",
      TiptapExtensions
  );

  const provider = new HocuspocusProvider({
      url: "ws://127.0.0.1:1234/",
      name: pageId,
      document: ydoc
  });

```

Example: 
- User 1 connects to an empty document, and inserts "Hello". These changes are synched with an external DB
- User 2 connects to the same document, fetching the content from the Database. When making the ydoc document using the code above, and passing this to the provider, the HocusPocus onLoadDocument function runs, and inserts the content again

How I have tried fixing the issue:
1. Making the ydoc in the frontend and sending it to the server, using the url param. Not possible because it doesn't seem to keep all necessary information when sending as a string
2. Sending the JSON to the server, and create the ydoc on the server. Not possible for me, since my extensions are a relatively big array, and needs to be updated manually both places since the HocusPocus server runs in its own enviornment.
3. Only pass the ydoc to the hocuspocusprovider in case no one has that document open. Not possible because I don't know before actually initializing the document, if it has content or not.
4. Manually paste in the content in the frontend 1000ms after the ydoc is made, and send those changes to the server. Would probably work, but seems to be a very inefficient way of doing it. 

**Steps to reproduce the bug**
Set up a simple project, and paste in some JSON and extensions using the functions provided above.

**Expected behavior**
I expect that when I pass in a name, it will only insert the document contents if no one else already has the document open.

**Screenshot, video, or GIF**

**Environment?**
 - operating system: Windows 11
 - browser: Brave
 - mobile/desktop: Desktop
 - Hocuspocus version: 
    - "@hocuspocus/provider": "^2.6.1",
    - "@hocuspocus/server": "^2.6.1",

**Additional context**

**Comment by janthurau** [comment]
@MrBisp this is working as intended, as you are merging your newly created ydoc with the ydoc that the server already has in place. You will need to make sure to create the ydoc only once. If you want to load initial content, please check out this guide: https://tiptap.dev/hocuspocus/guides/persistence - you'll need to load that on the server.
