### ISSUE TITLE
What will happen if we don't store whole ydoc

### ISSUE THREAD

**Issue by jiawei686** [ueberdosis/hocuspocus#731]
I've read the your document and aware of we should save uintarray to keep ydoc structure to make it mergable. What will happen if we store data.document.get('content', Y.XmlText) and transform it to origin objects ? Our application need to check permission on every content lines while connecting.

**Comment by jiawei686** [comment]
https://docs.slate-yjs.dev/walkthroughs/collaboration-hocuspocus
In your document slate example link, I saw slate-yjs transform slate nodes to ydoc. Does it make sense if we transform slate nodes to ydoc instead of using ydoc uintarray?

**Comment by janthurau** [comment]
If you don't store the entire ydoc, the syncing won't work properly (i.e. when you re-create the ydoc from json or any other structure, the content will duplicate). You can still use the JSON or also XML or any other structure from within the ydoc, but the provider always needs the full ydoc to work properly.
