### ISSUE TITLE
Is it possible for provider to fetch document by default

### ISSUE THREAD

**Issue by jiawei686** [ueberdosis/hocuspocus#732]
<img width="945" alt="image" src="https://github.com/ueberdosis/hocuspocus/assets/12953093/640b94aa-5906-4b0e-9dc5-8966c579daaf">
Is it possible for provider to fetch document from hocuspocus server by default instead of creating a new ydoc ? Now it sems that we could only get current ydoc by http then connect websocket by provider

**Comment by janthurau** [comment]
The provider is actually fetching the document from the hocuspocus server, but you need to least create the local instance first. Not sure why you think that it is fetched via HTTP? That's not the case.

Btw, this is not an issue :) Please check out our Discord for questions: https://discord.gg/WtJ49jGshW
