### ISSUE TITLE
Documents are not stored before server shut down when `unloadImmediately` is set to false

### ISSUE THREAD

**Issue by shincurry** [ueberdosis/hocuspocus#738]
**Description**
When `unloadImmediately` is set to false, documents are not stored before server shut down.

No `onStoreDocument` called.
No `afterUnloadDocument` called.

**Steps to reproduce the bug**
1. `HocuspocusServer.configure` set `unloadImmediately` to `false`
3. register `onStoreDocument` hook for logging
4. frontend connect to any one document.
5. use `ctrl + c` shut down server.

**Expected behavior**

Output some logs printed from hooks to prove that the server stored documents before shutting down.

**Environment?**
 - operating system: macOS Sonoma 14.0
 - browser: Google Chrome 118.0.5993.117
 - mobile/desktop: desktop
 - Hocuspocus version: 2.7.1

**Comment by janthurau** [comment]
related to #711
