### ISSUE TITLE
Garbage collection is forcefully turned on on Hocuspocus server

### ISSUE THREAD

**Issue by EricHasegawa** [ueberdosis/hocuspocus#751]
**Description**
On the frontend of my editing app, I instantiate a `new HocuspocusProvider`, passing in a `yjsDoc` with `gc: false`.  I can log this on my front-end and confirm garbage collection is indeed turned off. When the doc gets sent to my server (either through `store` on a the `Database` extension or through the generic `onStoreDocument`, the passed in document has `document.gc = true`. This is preventing me from properly showing version snapshots :( 

**Steps to reproduce the bug**
1. Create a basic app with a provider, set `gc` to false.
2. Set up a basic server, when the document comes in through `onStore` or `onStoreDocument`, log `document.gc`, see that it is set to `true`. If you try to do something like `Y.createDocFromSnapshot` an error will be thrown.

**Expected behavior**
The document comes into the server and has `gc` set to false.

**Environment?**
 - operating system: NodeJS
 - browser: Any
 - mobile/desktop: Desktop
 - Hocuspocus version:
```
    "@hocuspocus/extension-database": "^2.4.0",
    "@hocuspocus/server": "^2.4.0",
    "@hocuspocus/transformer": "^2.4.0",
```

Please let me know if there's a way around this or if there's anything I'm doing wrong!

**Comment by douglasqian** [comment]
+1

**Comment by janthurau** [comment]
I think you just have to disable gc on the server as well, have you tried this?

```ts
new Hocuspocus({yDocOptions: {gc: false}})
```

**Comment by EricHasegawa** [comment]
This worked!! Thanks - had no idea this existed

**Comment by janthurau** [comment]
😎 just want to drop here that I wouldn't recommend doing this in the long run, as this will lead to an ever-growing history in the ydoc and will increase the memory and cpu requirements a lot (depending on how big the history got)

**Comment by alvintheodora** [comment]
Hi @janthurau , if the `Y.snapshot` approach and `createDocFromSnapshot` are not efficient in the long run as you mentioned above, and in addition to other users' experience posted in this [Garbage Collection and Version Snapshotting](https://discuss.yjs.dev/t/garbage-collection-and-version-snapshotting/1839), 
Then would the approach of using new `Y.Doc({ gc: true })` and saving the result of `Y.encodeStateAsUpdate` to a persistent database are more superior in the long run?
Like: 
```
import * as Y from 'yjs';

// Create a Y.Doc with garbage collection enabled
const ydoc = new Y.Doc({ gc: true });

// Make some changes to the document
const yText = ydoc.getText('content');
yText.insert(0, 'Hello, world!');

// Encode the full document state to store in the database
const encodedState = Y.encodeStateAsUpdate(ydoc);

// Store the encoded state in the persistence database, like mySQL
saveToDatabase({
  documentId: 'your-doc-id',
  encodedState,
  timestamp: new Date().toISOString(),
});
```
