### ISSUE TITLE
Provider downloads document content twice when syncing initially

### ISSUE THREAD

**Issue by aonnikov** [ueberdosis/hocuspocus#768]
**Description**

I see something weird in websocket messages between client and server. When syncing the document after connect, the server sends the same document content twice. It is something that is specific to Hocuspocus protocol? I don't see this for raw y-websocket, it sends content only once. When the document is large, this significantly increases time to sync.

I'm experimenting on live example here: https://templates.tiptap.dev/N9HkNRCwhN
Here is an example of messages between client and server. Two highlighted incoming messages contain identical document content.
<img width="900" alt="Screenshot 2023-12-29 at 13 48 04" src="https://github.com/ueberdosis/hocuspocus/assets/5876715/d281798d-bac6-4cbf-bcc3-2525a9bb8110">

Can someone explain, if it is expected and what is the need of sending it twice?

**Steps to reproduce the bug**
1. Go to https://templates.tiptap.dev/N9HkNRCwhN
2. Open Network tab in developer tools in the browser
3. Find websocket connection to the collaboration server and open details
4. See document content received twice

**Expected behavior**
I would expect the full document content to be sent only once. Increasing amount of data transferred between server and client increases response time and affects user experience.

**Screenshot, video, or GIF**
See above.

**Environment?**
 - OSX
 - Chrome 120.0.6099.129, Safari
 - Hocuspocus version: 2.5.0, 2.8.1

**Comment by janthurau** [comment]
thanks for the report! This will be fixed in the next release.
