### ISSUE TITLE
Do collaboration history and auto-versioning work?

### ISSUE THREAD

**Issue by DenysPoliarush** [ueberdosis/hocuspocus#780]
Hi guys! I have a question about Collaboration History and auto-versioning. I noticed that some of my documents do not have the latest version.
I have a document that was created on November 28, and there are 3 versions for November 28 with an interval of approximately 1 hour. After that, the document was updated many times, but no versions were created for this. 

In another document, I see the latest version as of January 4th, even though the document is updated daily. 

Did you disable auto-versioning and do I need to turn it on for each document by myself?

**Comment by janthurau** [comment]
hey @DenysPoliarush, please reach out to humans@tiptap.dev with your app ID and the document name, so we can have a look.
