### ISSUE TITLE
Add custome field to the Webhook

### ISSUE THREAD

**Issue by DenysPoliarush** [ueberdosis/hocuspocus#781]
Hi guys! Is it possible to add a custom field to the webhook payload? 

I need to know who made the changes in the document.
But the current webhook payload doesn't give me that.
![image](https://github.com/ueberdosis/hocuspocus/assets/66991536/4544e8e6-1614-4a70-a650-ba573dead4f5)

It would be great if I could pass the user token from the frontend to the server via this webhook.

If there is another method to know who made changes, please let me know.

Thanks!

**Comment by janthurau** [comment]
Hey @DenysPoliarush, this is related to Tiptap Collab, not the open source Hocuspocus :-) Please contact Tiptap at humans@tiptpa.dev regarding the cloud offering. Sorry for the late reply here ..
