### ISSUE TITLE
How to implement document versioning on Hocuspocus

### ISSUE THREAD

**Issue by ZhangMingZhao1** [ueberdosis/hocuspocus#840]
**The problem I am facing**
How to implement document versioning on Hocuspocus.
How tiptap's versioning plugin is implemented。I see that tiptap is storing data in full volume, how does the data flow through Hocuspocus when restoring a certain version and how does everyone else synchronize it

**The solution I would like**
I'm assuming it's using the yjs snapshot api?

**Additional context**
I would like to implement version restoration on my slate rich text in conjunction with Hocuspocus, so that when one person restores a version, others can synchronize to that version as well, and I'm not sure where would be a good place to do that

**Comment by janthurau** [comment]
Hi @ZhangMingZhao1, the versioning feature is part of Tiptap Collab and thus not available in the open source version Hocuspocus. Tiptap Collab is compatible with slate, so feel free to just use the cloud offering :)

**Comment by alvintheodora** [comment]
Hi @janthurau , If we have Entry subscription, but don't use the Tiptap Cloud or On-Premises images (which is I assumed to be available upon subscribing to Enterprise subscription), can we use the the Collab History Extension in our open source version Hocuspocus?

**Comment by janthurau** [comment]
hey @alvintheodora, unfortunately the history extension doesnt work with Hocuspocus, you'll need Tiptap Cloud (or on-prem) to use it.

However, ofc you can implement it yourself, for example using the demo that you linked. Just note that it requires garbage collection disabled.

**Comment by bohdan-mykhailenko** [comment]
@alvintheodora  Did you manage how to deal with it?

I have the same requirement to build 'clone' of `tiptap` extension with `yjs` + `pm` only
