### ISSUE TITLE
Call applyUpdate duplicatedly when using hocuspocus-database

### ISSUE THREAD

**Issue by shincurry** [ueberdosis/hocuspocus#848]
**Description**

When using hocuspocus-database, the `update` data fetched from the database will be applied (by calling `Y.applyUpdate`) to the document twice.

https://github.com/ueberdosis/hocuspocus/blob/edd7034aece9ba41dcb4efff1207fd06624f319d/packages/server/src/Hocuspocus.ts#L473-L483

`loadedDocument` and `document` are the same instance

https://github.com/ueberdosis/hocuspocus/blob/edd7034aece9ba41dcb4efff1207fd06624f319d/packages/extension-database/src/Database.ts#L44-L52

**Possible solution?**

`Database.onLoadDocument` should not return document?

**Comment by janthurau** [comment]
Thanks!!
