### ISSUE TITLE
Root shared objects have AbstractType type on the server

### ISSUE THREAD

**Issue by andevdokimov** [ueberdosis/hocuspocus#853]
**Description**
Shared objects inside the yDoc.shared have AbstractType and it does seem impossible to figure out the exact type (YMap/YArray etc).

**Steps to reproduce the bug**
```
Say, on client side I have yDoc. Then I create two shared root objects:
const yMap = yDoc.getMap('testMap');
// fill yMap with some data
const yArray = yDoc.getArray('testArray');
// fill yArray with some data
```

Then when you inspect dDoc.share on the server side, this map will have two items of AbstractType type

Is this kind of expected or bug?
If this is expected, then how to understand the particular type of the root objects?

Thanks.

**Comment by ilya2204** [comment]
As far as I know, this is the behavior of yjs. Until someone explicitly calls getMap/getArray in the document, the document will not contain information about a specific type.
