### ISSUE TITLE
tiptap HocuspocusProvider  error in editing Unexpected end of array

### ISSUE THREAD

**Issue by Mrezagolbaba** [ueberdosis/hocuspocus#863]
**Description**
I tried to generate live collaboration with Tiptap and HocuspocusProvider in Reactjs the web socket is working well but when I want to start editing I see a weird error that is stopping me from editing the document

**Steps to reproduce the bug**
by starting editing we will see the attached image 

**Expected behavior**

**Screenshot, video, or GIF**
![image](https://github.com/user-attachments/assets/0424b32b-d47e-4334-ac4d-1acee82a2ff3)

**Environment?**
 - operating system:OSX
 - browser:Chroume
 - mobile/desktop:Desktop
 - Hocuspocus version:^2.13.7

**Additional context**
```
const provider = new HocuspocusProvider({
    url: "ws://localhost:8000/ws/document/edit/3f798b14-4635-4450-bc66-b05b04fbfb8f?token=" + TEST_TOKEN,
    name: "3f798b14-4635-4450-bc66-b05b04fbfb8f",
    document: ydoc,
});

function Tiptap({
    content = '',
    editable = true,
    placeholder = "Type '/' for actions…",
}: TiptapProps) {
    const extensions: Extensions = [
        Collaboration.configure({
            document: provider.document,
        }),
        CollaborationCursor.configure({
            provider: provider,
            user: {
              name: 'Cyndi Lauper',
              color: '#f783ac',
            },
          }),
    ]
    const editor = useEditor({
        content,
        extensions,
        editable,
        onUpdate: ({ editor }) => {
            console.log(editor.getJSON())
        },
    })

    if (!editor) {
        return null
    }

    return (
      
            <div className="WhiteCard">
                <EditorContent editor={editor} />
            </div>
    )
}

export default Tiptap


```

**Comment by vinceprofeta** [comment]
@Mrezagolbaba Any luck here?

**Comment by janthurau** [comment]
which line is causing this error exactly (unminified)?
Could be an issue caused by rerendering of the component, or an issue on the hocuspocus server.

Please provider a sandbox, or check out our playground repo, as this is most likely not a bug but an implementation issue.

**Comment by liwei511** [comment]
when use nextjs, same error
