### ISSUE TITLE
Websockets keep reconnecting when server is run with Bun

### ISSUE THREAD

**Issue by roschlau** [ueberdosis/hocuspocus#878]
Full disclosure upfront: I'm pretty sure the root cause of this is a bug in Bun itself, which I've already filed [here](https://github.com/oven-sh/bun/issues/15247). However, I don't know how long that could take to fix on their end, while adding a workaround in Hocuspocus seems to be very simple and not have any side-effects as far as I can tell. This workaround would be to change [this line](https://github.com/ueberdosis/hocuspocus/blob/1c18ee7499cfed189fbf11111fb1c52810bb0210/packages/server/src/Connection.ts#L186) from `this.webSocket.ping()` to `this.webSocket.ping('')`. I'm happy to create a pull request for that, if there are no objections.

**Description**
We're building a Hocuspocus-powered server that's supposed to be run in [Bun](https://bun.sh/), rather than in NodeJS. With this setup, everything works great except websocket Pings are not sent correctly to the client, which means the client never sends a Pong back, causing Hocuspocus to kill the websocket after the timeout with the message "4408 Connection Timeout". The client then reacts by creating a new connection, until that one also gets killed, producing an endless loop.

**Steps to reproduce the bug**
1. Make sure Bun is installed
2. In an empty directory, run `bun init`, accept the default values it's asking for
3. Run `bun install @hocuspocus/server`
4. Replace the content of `index.ts` with the example code from the [Getting Started guide](https://tiptap.dev/docs/hocuspocus/getting-started#usage)
5. Add a timeout to the server config in `index.ts` (e.g. `timeout: 5 * 1000`)
6. Run `bun run index.ts`
7. Connect with any Hocuspocus client from the browser and observe the websocket messages

The websocket will be repeatedly closed (4408) and reconnected ad inifitum. No Ping or Pong messages are sent.

**Expected behavior**
The websocket stays open as long as the client is active, and Ping and Pong messages are regularly exchanged as configured by the timeout.

**Environment?**
 - operating system: Windows, Alpine Linux (in Docker on Ubuntu)
 - browser: N/A
 - mobile/desktop: N/A
 - Hocuspocus version: 2.13.7

**Comment by janthurau** [comment]
I wanted to modify the websocket ping already for a long time, but haven't had time yet. I've also had issues with it in the past.

Bun seems to have fixed it though, at least they closed their issue :) Would be great if you could let us know if that fixes the issue for you.

**Comment by roschlau** [comment]
Yeah, they were really quick with this! Will report back once the update has landed and I was able to test it 👍

**Comment by roschlau** [comment]
Oh btw, @janthurau unless I'm misunderstanding what you're talking about, at least in Firefox you can enable ping/pong/close messages by enabling the "Control" option in this dropdown:
![image](https://github.com/user-attachments/assets/c6c0a8eb-4fed-4cd9-8586-44eef38a56d5)
The empty messages in the background of that screenshot are the pings. If the ping has a payload it will show up there normally as well

**Comment by roschlau** [comment]
@janthurau can confirm that the most recent Bun version (>= v1.1.37) fixes the problem for us!
