### ISSUE TITLE
Type issue in version 2.14.0

### ISSUE THREAD

**Issue by giacomorebonato** [ueberdosis/hocuspocus#879]
**Description**

2.14.0 seems to be a breaking change because it breaks the type of the extensions' invokation.

1. checkout [this repository](https://github.com/giacomorebonato/fastrat/blob/main/src/collab/collab-plugin.ts#L16-L38)
2. `pnpm install`
3. execute `pnpm test:types`
4. [link to the failure on CI](https://github.com/giacomorebonato/fastrat/actions/runs/11944627370/job/33295889208?pr=804)

**Expected behavior**

I'd expect a breaking change in a major release, but if I need to change anything myself, I am ready to adapt.

**Screenshot, video, or GIF**

![Screenshot 2024-11-21 at 20 18 15](https://github.com/user-attachments/assets/6eac96ef-ee68-4a42-890d-6de167cf6863)

**Environment?**
 - operating system: macOS
 - browser: Node
 - mobile/desktop: 
 - Hocuspocus version: 2.14.0

**Additional context**

Please reach out if I can test anything out for you. Thanks for this amazing library!

**Comment by janthurau** [comment]
hm, this looks like you loaded @hocuspocus/server 2.13.7 and 2.14.0 simultaneously - can you check if this is the case? I'm not sure how pnpm works, but usually that would be shown with `npm why @hocuspocus/server`

**Comment by giacomorebonato** [comment]
Works now. Thank you!
