### ISSUE TITLE
Socket.io support

### ISSUE THREAD

**Issue by hanspagel** [ueberdosis/hocuspocus#95]
For people using Socket.io it would be great to integrate hocuspocus, like it’s already possible with Express.

**Comment by YousefED** [comment]
> Any of the fallback solutions (HTTP long pulling, flash sockets (Adobe Flash), server sent events, ..) are not suitable for modern shared editing applications

Could you explain this @dmonad? (I'm in an environment where websockets are potentially blocked - so the current idea is to fallback to long polling
